import { readFileSync,writeFileSync } from 'node:fs'
const tree=process.argv[2]??process.cwd()
const {evaluateSurveyStatisticalFamilyV1:evaluate}=await import(`${tree}/kun/src/engineering/survey-statistical-family.ts`)
const base=import.meta.dir
function distribution(kind:string,df:number|null){return kind==='normal'?{kind,tail:'two-sided',statisticBasis:'standardized-by-known-prior-scale',scaleBasis:'caller-declared-known-prior-standard-deviation',priorStandardDeviation:1,scaleUnit:'m'}:kind==='student-t'?{kind,tail:'two-sided',statisticBasis:'externally-studentized',degreesOfFreedom:df}:{kind,tail:'upper',statisticBasis:'quadratic-form-divided-by-known-prior-variance',degreesOfFreedom:df,scaleBasis:'caller-declared-known-prior-standard-deviation',priorStandardDeviation:1,scaleUnit:'m'}}
function request(kind:string,df:number|null,value:number,alpha=.05,m=1){return{schemaVersion:1,familyId:'independent-oracle',declaration:'caller-declared-before-observing-statistics',statisticPrecision:'caller-declared-exact-scalar-inputs-no-upstream-error-propagation',correction:'bonferroni',alpha,members:Array.from({length:m},(_,i)=>({id:`member-${i}`,sourceAnchor:'synthetic-independent-review',distribution:distribution(kind,df)})),statistics:[{memberId:'member-0',status:'available',value}]}}
const cases=['survey-statistical-family-review-tail-cases.json','survey-statistical-family-review-random-cases.json'].flatMap(file=>JSON.parse(readFileSync(`${base}/${file}`,'utf8')))
const results=cases.map((c:any)=>{const out=evaluate(request(c.kind,c.df,c.statistic));return {...c,result:out.results?.[0]??out}})
const criticals=JSON.parse(readFileSync(`${base}/survey-statistical-family-review-critical-cases.json`,'utf8')).map((c:any)=>{const points=['predecessor','nearest','successor','farBelow','farAbove'].map(point=>{const out=evaluate(request(c.kind,c.df,c[point],c.alpha,c.familySize));if(out.outcome!=='evaluated'||out.denominator!==c.familySize||out.results.length!==c.familySize)throw new Error('family denominator discrepancy');if(out.results.slice(1).some((r:any)=>r.status!=='unavailable'))throw new Error('missing member state lost');return{point,result:out.results[0]}});return{...c,points}})
const mixed=request('normal',null,2.5,.05,4);mixed.statistics.push({memberId:'member-1',status:'unavailable',reason:'upstream-unavailable'}as any,{memberId:'member-2',status:'undetectable',reason:'null-space'}as any,{memberId:'member-3',status:'available',value:36});const mixedResult=evaluate(mixed)
const malformed=[{...request('normal',null,0),alpha:0},{...request('student-t',2.5,1)},{...request('normal',null,1),declaration:'observed-then-selected'},request('chi-square',2,-1),request('normal',null,35.0001),request('student-t',1,1e16+2)]
const extraResults=malformed.map(input=>({input,result:evaluate(input)}))
writeFileSync(`${base}/survey-statistical-family-review-probe-results.json`,JSON.stringify({results,criticals,mixedResult,extraResults},null,2)+'\n')
const resolved=results.filter((x:any)=>x.result.status==='calculated')
console.log(JSON.stringify({cases:results.length,counts:results.reduce((a:any,x:any)=>(a[x.result.status]=(a[x.result.status]??0)+1,a),{}),maxRelativeTailError:Math.max(...resolved.map((x:any)=>Math.abs(x.result.pValue/Number(x.p120)-1))),maxLogError:Math.max(...resolved.map((x:any)=>Math.abs(x.result.logPValue-Number(x.logP120)))),criticalCases:criticals.length,criticalNearestWrong:criticals.filter((x:any)=>x.points.slice(0,3).some((y:any)=>y.result.status!=='calculated'||y.result.comparison!=='boundary-unresolved')),criticalFarWrong:criticals.filter((x:any)=>x.points[3].result.comparison!=='p-above-adjusted-alpha'||x.points[4].result.comparison!=='p-below-adjusted-alpha'),mixed:mixedResult},null,2))
