// @vitest-environment happy-dom
import {act,createElement} from '#repo/node_modules/react/index.js'
import {createRoot} from '#repo/node_modules/react-dom/client.js'
import {Buffer as NodeBuffer} from 'node:buffer'
import {webcrypto} from 'node:crypto'
import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {SurveyAdvancedTrialsWorkspaceService as Service} from '#repo/kun/src/engineering/survey-advanced-trials-workspace.ts'
import {advancedTrialTestRequest,maximumNewAdvancedTrialRequest} from '#repo/kun/src/engineering/survey-advanced-trials-test-helpers.ts'
import {SurveyAdvancedModelWorkspace} from '#repo/src/renderer/src/components/engineering/SurveyAdvancedModelWorkspace.tsx'
import i18n from '#repo/src/renderer/src/i18n.ts'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
const request=vi.mocked(rendererRuntimeClient.runtimeRequest)
let root:any,host:HTMLDivElement
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(crypto,'subtle',{configurable:true,value:webcrypto.subtle});await i18n.changeLanguage('en');host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{vi.unstubAllGlobals();await act(async()=>root.unmount());host.remove();request.mockReset()})
function real(kind:string,max=false,basis='Independent synthetic model, not professional approval.') {const dir=mkdtempSync(join(tmpdir(),'integration-gui-'));const p={id:'gui-review',revision:1,workspace:dir+'/workspace'};const s=new Service({rootDir:dir,getProject:(id:string)=>id===p.id?p:null});try{const q=max?maximumNewAdvancedTrialRequest(kind):advancedTrialTestRequest(kind);q.modelBasisStatement=basis;const summary=s.createTrial(p.id,NodeBuffer.from(JSON.stringify(q)));return {summary,record:s.getTrial(p.id,summary.id),binding:{projectId:p.id,projectRevision:1,workspaceRoot:p.workspace}}}finally{s.close();rmSync(dir,{recursive:true,force:true})}}
const button=(key:string)=>[...host.querySelectorAll('button')].find(n=>n.textContent===i18n.t(key))!
async function click(n:HTMLElement){await act(async()=>n.click())}
async function settle(fn:()=>void){let e;for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,5))});try{fn();return}catch(x){e=x}}throw e}
async function restore(f:any){request.mockImplementation(async path=>({ok:true,status:200,body:path.includes('?')?JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null}):JSON.stringify(f.record)}));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await settle(()=>expect(host.textContent).toContain(i18n.t('advancedSavedRecord')))}
it.each(['huber','statistical-family'])('renders full maximum %s and conclusion boundaries without Buffer',async kind=>{const f=real(kind,true);vi.stubGlobal('Buffer',undefined);await restore(f);expect(host.querySelector('[role=alert]')).toBeNull();expect(host.textContent).not.toMatch(/\bNaN\b|\bInfinity\b|\bundefined\b/);expect(host.textContent).not.toMatch(/[㐀-鿿]/);if(kind==='huber'){const trace=host.querySelector(`[aria-label="${i18n.t('advancedIterationTrace')}"]`)!;expect(trace.querySelectorAll('details')).toHaveLength(201);expect(trace.querySelectorAll('details[open]')).toHaveLength(1);expect(host.textContent).toContain('o127');expect(host.textContent).toContain(i18n.t('advancedIterationLimit'));expect(host.textContent).not.toContain(i18n.t('advancedParameters'));expect(trace.querySelectorAll('table')).toHaveLength(1);const first=trace.querySelector('details')!;await act(async()=>{first.open=true;first.dispatchEvent(new Event('toggle'))});expect(first.open).toBe(true);expect(trace.querySelectorAll('details[open]')).toHaveLength(1);expect(trace.querySelectorAll('table')).toHaveLength(1);expect(first.querySelector('tbody tr')).not.toBeNull()}else{expect(host.querySelectorAll('tbody tr')).toHaveLength(256);expect(host.textContent).toContain('m255');expect(host.textContent).toContain(i18n.t('advancedStatisticalNoDecision'));expect(host.textContent).toContain(i18n.t('advancedStatisticalInterval'));let distinct=0;for(const member of f.record.result.results){const distribution=f.record.result.request.members.find((x:any)=>x.id===member.memberId).distribution;if('degreesOfFreedom'in distribution)expect(host.textContent).toContain(i18n.t('advancedDistributionDf',{df:distribution.degreesOfFreedom}));if('priorStandardDeviation'in distribution)expect(host.textContent).toContain(i18n.t('advancedDistributionPriorScale',{sigma:String(distribution.priorStandardDeviation),unit:distribution.scaleUnit}));if(member.status!=='calculated')continue;const [low,high]=member.numericalResolutionInterval;expect(low).toBeLessThan(high);expect(host.textContent).toContain('['+String(low)+', '+String(high)+']');expect(host.textContent).toContain(String(member.criticalMagnitude));if(Number(low.toPrecision(12))===Number(high.toPrecision(12)))distinct++}expect(distinct).toBeGreaterThan(0)}})
it.each(['huber','statistical-family'])('exports exact Unicode %s and blocks late native save after project change',async kind=>{const f=real(kind,false,'  原始依据😀\n完整保留。');const save=vi.fn().mockResolvedValue({ok:true,path:'/review/trial.json'});Object.assign(window,{workwise:{saveWorkspaceFileAs:save}});vi.stubGlobal('Buffer',undefined);await restore(f);await click(button('advancedExport'));await settle(()=>expect(save).toHaveBeenCalledOnce());const saved=save.mock.calls[0][0];expect(NodeBuffer.from(saved.dataBase64,'base64').toString('utf8')).toBe(JSON.stringify(f.record)+'\n');expect(saved.workspaceRoot).toBe(f.binding.workspaceRoot);await settle(()=>expect(host.textContent).toContain('/review/trial.json'));let release:any;request.mockImplementationOnce(()=>new Promise(r=>{release=r}));await click(button('advancedExport'));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,projectId:'other'},runtimeReady:true})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(save).toHaveBeenCalledOnce();expect(host.textContent).not.toContain(f.summary.id)})
it.each(['workspace','revision','runtime'])('drops late restore on %s scope change',async kind=>{const f=real('statistical-family');let release:any;request.mockImplementation(async path=>path.includes('?')?{ok:true,status:200,body:JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null})}:new Promise(r=>{release=r}));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,...(kind==='workspace'?{workspaceRoot:'/other'}:kind==='revision'?{projectRevision:2}:{})},runtimeReady:kind!=='runtime'})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(host.textContent).not.toContain(i18n.t('advancedSavedRecord'));expect(host.textContent).not.toContain(f.summary.id)})
