import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {afterEach,it,expect,vi} from 'vitest'
import Database from '#repo/node_modules/better-sqlite3/lib/index.js'
import {SurveyAdvancedTrialsWorkspaceService as Service} from '#repo/kun/src/engineering/survey-advanced-trials-workspace.ts'
import {SurveyAdvancedTrialSummaryV1} from '#repo/kun/src/contracts/survey-advanced-trials-workspace.ts'
import {advancedTrialTestRequest} from '#repo/kun/src/engineering/survey-advanced-trials-test-helpers.ts'
import {fixture,model,envelope} from './fixtures'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
import {readAdvancedTrial,exportAdvancedTrial,validateAdvancedTrialInput} from '#repo/src/renderer/src/agent/survey-advanced-trials-client.ts'
const mock=vi.mocked(rendererRuntimeClient.runtimeRequest);afterEach(()=>{vi.unstubAllGlobals();mock.mockReset()})
const sha=(b:any)=>createHash('sha256').update(b).digest('hex');function canonical(v:any):string{if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}const digest=(v:any)=>sha(canonical(v))
it.each(['generalized-w','vce','huber','statistical-family','reference-datum'])('restores real raw Unicode %s without Buffer with new count fields isolated',async kind=>{const q=kind==='reference-datum'?envelope():advancedTrialTestRequest(kind);q.modelBasisStatement='  中文😀\n保留原始依据。';const f=fixture(q);expect(f.record.requestJson).toBe(f.raw.toString());expect(f.record.declarationJson).toBe(q.declarationJson);if(kind==='reference-datum'){expect(f.summary).toMatchObject({observationCount:0,parameterCount:0,pointCount:3,referenceCount:2});expect(f.summary).not.toHaveProperty('familyMemberCount')}else{expect(f.summary).not.toHaveProperty('pointCount');expect(f.summary).not.toHaveProperty('referenceCount')}mock.mockResolvedValue({ok:true,status:200,body:JSON.stringify(f.record)} as any);vi.stubGlobal('Buffer',undefined);expect(await readAdvancedTrial(f.binding,f.summary)).toEqual(f.record);expect(await exportAdvancedTrial(f.binding,f.summary)).toEqual(f.record)})
it.each(['near-PSD','singular','negative-weights'])('persists and restores reference outcome %s honestly',async kind=>{const f=fixture(envelope(model(kind)));if(kind==='singular')expect(f.record.result).toMatchObject({outcome:'unavailable',code:'reference-covariance-rank-or-conditioning'});if(kind==='near-PSD')expect(f.record.result.covarianceCheck).toMatchObject({classification:'semidefinite-or-unresolved-within-numerical-tolerance',matrixRepair:'none'});if(kind==='negative-weights'){expect(f.record.result.referenceWeights[0]).toBeCloseTo(1.5,14);expect(f.record.result.referenceWeights[1]).toBeCloseTo(-.5,14);expect(f.record.result.referenceWeights[2]).toBe(0);}mock.mockResolvedValue({ok:true,status:200,body:JSON.stringify(f.record)} as any);expect(await readAdvancedTrial(f.binding,f.summary)).toEqual(f.record)})
it('rejects summary dimension contamination and declaration ambiguity',()=>{const f=fixture();for(const patch of [{pointCount:undefined},{referenceCount:4},{observationCount:1},{parameterCount:1},{familyMemberCount:3}])expect(SurveyAdvancedTrialSummaryV1.safeParse({...f.summary,...patch}).success).toBe(false);const old=fixture(advancedTrialTestRequest('vce'));expect(SurveyAdvancedTrialSummaryV1.safeParse({...old.summary,pointCount:3,referenceCount:2}).success).toBe(false);const q=envelope();q.declarationJson=q.declarationJson.replace('"schemaVersion": 1','"schemaVersion":1,"schemaVersion":1');expect(validateAdvancedTrialInput(f.binding,q)).toBe(false)})
it('ten maximum records re-open and charge 191 then two 21-unit reads before limiting',()=>{const dir=mkdtempSync(join(tmpdir(),'reference-max-page-'));const p={id:'max-p',revision:1,workspace:dir};let ms=Date.parse('2026-09-20T00:00:00Z');const options={rootDir:dir,getProject:()=>p,clockMs:()=>ms,nowIso:()=>new Date(ms).toISOString()};let s=new Service(options);try{const ids=[];for(let i=0;i<10;i++){ms+=60001;ids.push(s.createTrial(p.id,Buffer.from(JSON.stringify(envelope(model('maximum',32),'maximum-reference-'+i)))).id)}s.close();s=new Service(options);const page=s.listTrials(p.id);expect(page.trials).toHaveLength(10);expect(page.unavailable).toEqual([]);expect(page.trials.every(x=>x.pointCount===32&&x.referenceCount===32&&x.observationCount===0&&x.parameterCount===0)).toBe(true);const a=s.getTrial(p.id,ids[0]);s.getTrial(p.id,ids[1]);expect(()=>s.getTrial(p.id,ids[2])).toThrow('rate-limit');expect(a.result.displacementCovariance).toHaveLength(32);expect(a.result.displacementCovariance.every((r:any)=>r.length===32)).toBe(true);expect(Buffer.byteLength(JSON.stringify(a))).toBeLessThan(4*1024*1024)}finally{s.close();rmSync(dir,{recursive:true,force:true})}})
it('rejects full-hash-restamped forged numeric displacement by actual replay',()=>{const dir=mkdtempSync(join(tmpdir(),'reference-forge-'));const p={id:'forge-p',revision:1,workspace:dir};const s=new Service({rootDir:dir,getProject:()=>p});let db:any;try{const summary=s.createTrial(p.id,Buffer.from(JSON.stringify(envelope())));db=new Database(join(dir,'survey-advanced-trials.sqlite3'));const row=db.prepare('SELECT * FROM advanced_trials WHERE id=?').get(summary.id);const record=JSON.parse(row.data_json);record.result.displacements[2]+=1;record.resultHash=digest(record.result);delete record.recordHash;record.recordHash=digest(record);row.record_hash=record.recordHash;row.data_json=JSON.stringify(record);const{storage_hash,request_bytes,declaration_bytes,...meta}=row;row.storage_hash=digest({...meta,request_bytes_sha256:sha(request_bytes),declaration_bytes_sha256:sha(declaration_bytes)});db.exec('DROP TRIGGER advanced_trials_no_update');const keys=Object.keys(row);db.prepare(`UPDATE advanced_trials SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).run(...keys.map(k=>row[k]),summary.id);expect(()=>s.getTrial(p.id,summary.id)).toThrow('integrity')}finally{db?.close();s.close();rmSync(dir,{recursive:true,force:true})}})
