import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {SurveyAdvancedTrialsWorkspaceService as Service} from '#repo/kun/src/engineering/survey-advanced-trials-workspace.ts'
export function model(kind='standard',n=3){const cov=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?2:0));const q:any={schemaVersion:1,model:'two-epoch-one-dimensional-declared-reference-datum',unit:'mm',method:'gls-reference-mean',referenceDeclaration:'caller-selected-reference-set-not-verified-stable',testingStrategy:'none-datum-comparison-only',firstEpoch:{id:'first-epoch',sourceAnchor:'independent-review-source-one',sourceSha256:'a'.repeat(64),covarianceBasis:'caller-declared-full-coordinate-covariance-not-cofactor',points:Array.from({length:n},(_,i)=>({id:'first-'+i,coordinate:i*10})),covariance:cov},secondEpoch:{id:'second-epoch',sourceAnchor:'independent-review-source-two',sourceSha256:'b'.repeat(64),covarianceBasis:'caller-declared-full-coordinate-covariance-not-cofactor',points:Array.from({length:n},(_,i)=>({id:'second-'+i,coordinate:i*10+[2,6,11][i%3]})),covariance:structuredClone(cov)},mapping:Array.from({length:n},(_,i)=>({id:'point-'+i,firstPointId:'first-'+i,secondPointId:'second-'+i})),referenceIds:['point-0','point-1'],dependence:{kind:'caller-declared-independent',sourceAnchor:'independent-review-dependence'}}
 if(kind==='maximum'){q.referenceIds=q.mapping.map((x:any)=>x.id);q.dependence={kind:'caller-declared-cross-covariance',sourceAnchor:'independent-full-cross',firstToSecondCovariance:Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?.5:0))}}
 if(kind==='negative-weights'){q.firstEpoch.covariance=[[.5,1,0],[1,2.5,0],[0,0,1]];q.secondEpoch.covariance=structuredClone(q.firstEpoch.covariance)}
 if(kind==='near-PSD'){q.referenceIds=['point-0','point-2'];q.method='equal-reference-mean';q.firstEpoch.covariance=[[1,1+5e-11,0],[1+5e-11,1,0],[0,0,1]];q.secondEpoch.covariance=structuredClone(q.firstEpoch.covariance)}
 if(kind==='singular'){q.firstEpoch.covariance=[[1,1,0],[1,1,0],[0,0,1]];q.secondEpoch.covariance=structuredClone(q.firstEpoch.covariance)}
 return q}
export function envelope(declaration=model(),key='independent-reference-review'){return {kind:'reference-datum',acknowledged:true,expectedProjectRevision:1,idempotencyKey:key,declarationJson:' \n'+JSON.stringify(declaration,null,2)+'\t',modelBasisStatement:'Independent synthetic review, no professional approval.'}}
export function fixture(q=envelope()){const dir=mkdtempSync(join(tmpdir(),'reference-integration-'));const project={id:'independent-project',revision:1,workspace:dir+'/workspace'};const s=new Service({rootDir:dir,getProject:(id:string)=>id===project.id?project:null});try {const raw=Buffer.from('\t '+JSON.stringify(q,null,2)+'\r\n');const summary=s.createTrial(project.id,raw),record=s.getTrial(project.id,summary.id);return {q,raw,summary,record,binding:{projectId:project.id,projectRevision:1,workspaceRoot:project.workspace}}}finally{s.close();rmSync(dir,{recursive:true,force:true})}}
