// @vitest-environment happy-dom
import {act,createElement} from '#repo/node_modules/react/index.js'
import {createRoot} from '#repo/node_modules/react-dom/client.js'
import {Buffer as NodeBuffer} from 'node:buffer'
import {webcrypto} from 'node:crypto'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {SurveyAdvancedModelWorkspace} from '#repo/src/renderer/src/components/engineering/SurveyAdvancedModelWorkspace.tsx'
import {fixture,model,envelope} from './fixtures'
import i18n from '#repo/src/renderer/src/i18n.ts'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
const request=vi.mocked(rendererRuntimeClient.runtimeRequest)
let root:any,host:HTMLDivElement
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(crypto,'subtle',{configurable:true,value:webcrypto.subtle});await i18n.changeLanguage('en');host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{vi.unstubAllGlobals();await act(async()=>root.unmount());host.remove();request.mockReset()})
const button=(key:string)=>[...host.querySelectorAll('button')].find(n=>n.textContent===i18n.t(key))!
async function click(n:HTMLElement){await act(async()=>n.click())}
async function settle(fn:()=>void){let e;for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,5))});try{fn();return}catch(x){e=x}}throw e}
async function restore(f:any){request.mockImplementation(async path=>({ok:true,status:200,body:path.includes('?')?JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null}):JSON.stringify(f.record)}));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await settle(()=>expect(host.textContent).toContain(i18n.t('advancedSavedRecord')))}
it.each(['en','zh'])('renders maximum reference full covariance/dependence and honest limits in %s without Buffer',async language=>{await i18n.changeLanguage(language);const f=fixture(envelope(model('maximum',32)));vi.stubGlobal('Buffer',undefined);await restore(f);const result=host.querySelector(`[aria-label="${i18n.t('advancedReferenceResults')}"]`)!;expect(result).not.toBeNull();expect(result.querySelectorAll('table')).toHaveLength(3);expect(result.querySelectorAll('table')[0].querySelectorAll('tbody tr')).toHaveLength(32);for(const table of [...result.querySelectorAll('table')].slice(1))expect(table.querySelectorAll('tbody td')).toHaveLength(1024);expect(result.textContent).toContain('first-31 → second-31');expect(result.textContent).toContain(i18n.t('advancedReferenceDependent'));expect(result.textContent).toContain(i18n.t('advancedReferenceBoundary'));expect(result.textContent).toContain(i18n.t('advancedReferencePositive'));expect(result.textContent).not.toMatch(/\bNaN\b|\bInfinity\b|\bundefined\b/);expect(result.textContent).not.toMatch(/advancedReference[A-Z]/);if(language==='en')expect(result.textContent).not.toMatch(/[㐀-鿿]/)})
it.each(['near-PSD','singular','negative-weights'])('renders %s without promotion or method fallback',async flavor=>{const f=fixture(envelope(model(flavor)));vi.stubGlobal('Buffer',undefined);await restore(f);const result=host.querySelector(`[aria-label="${i18n.t('advancedReferenceResults')}"]`)!;expect(result.textContent).toContain(i18n.t('advancedReferenceBoundary'));if(flavor==='near-PSD'){expect(result.textContent).toContain(i18n.t('advancedReferenceUnresolved'));expect(result.textContent).not.toContain(i18n.t('advancedReferencePositive'));expect(result.textContent).toContain(i18n.t('advancedReferenceEqual'));expect(result.querySelectorAll('table')).toHaveLength(3)}else if(flavor==='singular'){expect(result.textContent).toContain(i18n.t('advancedReferenceRank'));expect(result.textContent).toContain(i18n.t('advancedReferenceGls'));expect(result.textContent).not.toContain(i18n.t('advancedReferenceEqual'));expect(result.querySelectorAll('table')).toHaveLength(0)}else{expect(result.textContent).toContain(String(f.record.result.referenceWeights[1]));expect(result.textContent).toContain(i18n.t('advancedReferenceGls'))}})
it('exports complete Unicode reference record and suppresses late export after project switch',async()=>{const q=envelope(model('near-PSD'));q.modelBasisStatement='  指定参考复核😀\n完整原文  ';const f=fixture(q),save=vi.fn().mockResolvedValue({ok:true,path:'/review/reference.json'});Object.assign(window,{workwise:{saveWorkspaceFileAs:save}});vi.stubGlobal('Buffer',undefined);await restore(f);await click(button('advancedExport'));await settle(()=>expect(save).toHaveBeenCalledOnce());const data=save.mock.calls[0][0];expect(NodeBuffer.from(data.dataBase64,'base64').toString('utf8')).toBe(JSON.stringify(f.record)+'\n');expect(data.workspaceRoot).toBe(f.binding.workspaceRoot);expect(request.mock.calls.at(-1)[0]).toMatch(/\/export$/);await settle(()=>expect(host.textContent).toContain('/review/reference.json'));let release:any;request.mockImplementationOnce(()=>new Promise(r=>release=r));await click(button('advancedExport'));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,projectId:'changed'},runtimeReady:true})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(save).toHaveBeenCalledOnce();expect(host.textContent).not.toContain(f.summary.id)})
it.each(['workspace','revision','runtime'])('drops late reference restore after %s changes',async key=>{const f=fixture();let release:any;request.mockImplementation(async path=>path.includes('?')?{ok:true,status:200,body:JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null})}:new Promise(r=>release=r));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,...(key==='workspace'?{workspaceRoot:'/changed'}:key==='revision'?{projectRevision:2}:{})},runtimeReady:key!=='runtime'})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(host.textContent).not.toContain(f.summary.id);expect(host.textContent).not.toContain(i18n.t('advancedSavedRecord'))})
