import { describe, expect, it } from 'vitest'

describe('engineering workbench experience contract', () => {
  it('keeps conversation primary and reveals plans only when one exists', async () => {
    const nodeFs = 'node:fs/promises'
    const { readFile } = await import(/* @vite-ignore */ nodeFs)
    const source = await readFile(new URL('./EngineeringAiCommandCenter.tsx', import.meta.url), 'utf8')

    expect(source).toContain('engineering-conversation-surface')
    expect(source).toContain('<EngineeringComposer')
    expect(source).toContain('<MessageTimeline')
    expect(source).toContain("t('engineeringSession')")
    expect(source).toContain("t('engineeringEvidenceReturn')")
    expect(source).toContain("t('engineeringTypedPlan')")
    expect(source).toContain('{scopedPlan ? <section')
    expect(source).not.toContain('localStorage')
    expect(source).not.toContain('await sendMessage(')
    expect(source).toContain('/v1/engineering/ai/plans?')
  })

  it('keeps one mounted conversation alongside every classic view and a complete view selector', async () => {
    const nodeFs = 'node:fs/promises'
    const { readFile } = await import(/* @vite-ignore */ nodeFs)
    const source = await readFile(new URL('./EngineeringWorkspaceView.tsx', import.meta.url), 'utf8')

    expect(source).toContain("${tab === 'ai-command' ? 'engineering-agent-route' : 'engineering-classic-route'}")
    expect(source).toContain('data-testid="engineering-workspace-header"')
    expect(source).toContain('data-testid="engineering-persistent-chat"')
    expect(source).toContain('id="engineering-view-select"')
    expect(source).toContain('const STAGES: ReadonlyArray<StageDefinition>')
    expect(source).toContain('engineeringStageImport')
    expect(source).toContain('engineeringStageAdjustment')
    expect(source).toContain('engineeringStageDelivery')
    expect(source.match(/<EngineeringAiCommandCenter/g)).toHaveLength(1)
    expect(source.indexOf('<EngineeringAiCommandCenter')).toBeLessThan(source.indexOf("{tab !== 'ai-command' ? <div className=\"engineering-classic-shell"))
    expect(source).toContain("('.engineering-persistent-chat textarea')?.focus()")
    expect(source).toContain('data-testid="engineering-summary-strip"')
    expect(source).toContain('engineeringSummaryReadiness')
    expect(source).toContain('engineeringSummaryClosure')
    expect(source).toContain('/v1/engineering/survey/networks?projectId=')
    expect(source).toContain('/v1/engineering/adjustments?projectId=')
    expect(source).toContain('surveyPointCount?.toLocaleString(locale)')
    expect(source).toContain('surveyClosureValue')
    expect(source).toContain('surveyPrecision.maxPointStdDev')
    expect(source).toContain("'archive-only'")
    expect(source).toContain("'converter-required'")
    expect(source).toContain("'gnss-processing-required'")
  })

  it('uses an engineering-specific empty state before a project thread exists', async () => {
    const nodeFs = 'node:fs/promises'
    const { readFile } = await import(/* @vite-ignore */ nodeFs)
    const source = await readFile(new URL('./EngineeringAiCommandCenter.tsx', import.meta.url), 'utf8')

    expect(source).toContain('data-testid="engineering-ai-empty-state"')
    expect(source).toContain("t('engineeringNoProject')")
    expect(source).toContain("t('engineeringActionCreateProject')")
    expect(source).not.toContain('Start your agent rhythm')
    expect(source).not.toContain('WorkWise Runtime usage')
    expect(source).toContain('timelineHasActivity')
    expect(source).toContain("t('engineeringAiTitle')")
    expect(source).toContain("t('engineeringRuntimeRetry')")
    expect(source).toContain("t('engineeringCheckConfig')")
    expect(source).toContain("t('engineeringRuntimeNotConnected')")
    expect(source).toContain("probeRuntime('user')")
  })

  it('keeps survey work in professional point, observation, topology, and result views', async () => {
    const nodeFs = 'node:fs/promises'
    const { readFile } = await import(/* @vite-ignore */ nodeFs)
    const source = await readFile(new URL('./SurveyAdjustmentPanel.tsx', import.meta.url), 'utf8')

    expect(source).toContain("t('surveySectionNetwork')")
    expect(source).toContain("t('surveySectionObservations')")
    expect(source).toContain("t('surveySectionPoints')")
    expect(source).toContain("t('surveySectionResult')")
    expect(source).toContain("t('surveyResidualsOutliers')")
    expect(source).toContain("t('surveyRunAdjustment')")
    expect(source).toContain("t('surveyAdvancedJson')")
    expect(source).toContain("t('surveyAskAgent')")
    expect(source).toContain('lg:grid-cols-[190px_minmax(0,1fr)] 2xl:grid-cols-[190px_minmax(0,1fr)_260px]')
    expect(source).toContain('grid gap-3 2xl:grid-cols-[minmax(0,1fr)_260px]')
    expect(source).toContain('survey-instrument-strip')
    expect(source).toContain("t('surveyPointSummary')")
    expect(source).toContain('标准化残差 > 3σ')
    expect(source).toContain("t('surveyAdjustedX', { unit: linearUnit })")
    expect(source).toContain("t('surveyPointError', { unit: linearUnit })")
    expect(source).toContain("t('surveyAngularNorm')")
    expect(source).toContain("t('surveyDeformationTitle')")
    expect(source).toContain('/v1/engineering/deformations')
    expect(source).toContain('dX / dY / dH（m）')
    expect(source).toContain("t('surveyPairsJson')")
    expect(source).toContain("t('surveyStabilityThreshold')")
    expect(source).toContain('/v1/engineering/survey/networks?projectId=')
    expect(source).toContain("t('surveyExistingNetwork')")
    expect(source).toContain("setSection(preferredSectionRef.current ?? (restoredAdjustment ? 'result' : 'network'))")
    expect(source).toContain("t('surveyPreflight')")
    expect(source).toContain("t('surveyFormatFilterAria')")
    expect(source).toContain("t('surveyReadinessFilterAria')")
    expect(source).toContain("t('surveyDispositionGnss')")
    expect(source).toContain("t('surveyDispositionConverter')")
    expect(source).toContain('Leica GSI-8')
    expect(source).toContain('Trimble JobXML / JXL')
    expect(source).toContain('RTCM 3')
  })
})
