import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {afterEach,it,expect,vi} from 'vitest'
import Database from '#repo/node_modules/better-sqlite3/lib/index.js'
import {SurveyAdvancedTrialsWorkspaceService as Service} from '#repo/kun/src/engineering/survey-advanced-trials-workspace.ts'
import {SurveyAdvancedTrialSummaryV1} from '#repo/kun/src/contracts/survey-advanced-trials-workspace.ts'
import {advancedTrialTestRequest} from '#repo/kun/src/engineering/survey-advanced-trials-test-helpers.ts'
import {fixture,model,envelope} from './fixtures'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
import {readAdvancedTrial,exportAdvancedTrial,validateAdvancedTrialInput} from '#repo/src/renderer/src/agent/survey-advanced-trials-client.ts'
const mock=vi.mocked(rendererRuntimeClient.runtimeRequest);afterEach(()=>{vi.unstubAllGlobals();mock.mockReset()})
const sha=(b:any)=>createHash('sha256').update(b).digest('hex');function canonical(v:any):string{if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}const digest=(v:any)=>sha(canonical(v))
it.each(['generalized-w','vce','huber','statistical-family','reference-datum','static-incremental'])('restores real raw Unicode %s without Buffer with new count fields isolated',async kind=>{const q=kind==='static-incremental'?envelope():advancedTrialTestRequest(kind);q.modelBasisStatement='  中文😀\n保留原始依据。';const f=fixture(q);expect(f.record.requestJson).toBe(f.raw.toString());expect(f.record.declarationJson).toBe(q.declarationJson);if(kind==='static-incremental'){expect(f.summary).toMatchObject({observationCount:3,parameterCount:1,baseObservationCount:2,appendedObservationCount:1});expect(f.summary).not.toHaveProperty('pointCount')}else{expect(f.summary).not.toHaveProperty('baseObservationCount');expect(f.summary).not.toHaveProperty('appendedObservationCount')}mock.mockResolvedValue({ok:true,status:200,body:JSON.stringify(f.record)} as any);vi.stubGlobal('Buffer',undefined);expect(await readAdvancedTrial(f.binding,f.summary)).toEqual(f.record);expect(await exportAdvancedTrial(f.binding,f.summary)).toEqual(f.record)})
it.each(['stale','zero-sse'])('persists and restores %s honestly with frozen-model fingerprint',async kind=>{const f=fixture(envelope(model(kind)));if(kind==='stale')expect(f.record.result).toMatchObject({outcome:'unavailable',code:'base-fingerprint-mismatch'});else expect(f.record.result).toMatchObject({outcome:'calculated'});mock.mockResolvedValue({ok:true,status:200,body:JSON.stringify(f.record)} as any);vi.stubGlobal('Buffer',undefined);expect(await readAdvancedTrial(f.binding,f.summary)).toEqual(f.record)})
it('preserves known prior covariance despite posterior factor 28',()=>{const f=fixture();expect(f.record.result.updatedFit.parameters[0]).toBeCloseTo(4,14);expect(f.record.result.updatedFit.aprioriParameterCovariance[0][0]).toBeCloseTo(1/3,14);expect(f.record.result.updatedFit.posteriorVarianceFactorEstimate).toBeCloseTo(28,12);expect(f.record.result.priorRuntimeStateVerified).toBe(false)})
it('summary cannot mix old/new counts or expand legacy observation limits',()=>{const f=fixture();for(const patch of [{baseObservationCount:undefined},{appendedObservationCount:2},{observationCount:4},{parameterCount:17},{familyMemberCount:3},{pointCount:3}])expect(SurveyAdvancedTrialSummaryV1.safeParse({...f.summary,...patch}).success).toBe(false);for(const kind of ['generalized-w','vce','huber','statistical-family','reference-datum']){const old=fixture(advancedTrialTestRequest(kind));expect(SurveyAdvancedTrialSummaryV1.safeParse({...old.summary,baseObservationCount:2,appendedObservationCount:1}).success).toBe(false);expect(SurveyAdvancedTrialSummaryV1.safeParse({...old.summary,observationCount:129}).success).toBe(false)}})
it('maximum 256/16/128 ten-item page costs 191 with two further reads before rate limit',()=>{const dir=mkdtempSync(join(tmpdir(),'static-max-page-'));const p={id:'maximum-static-project',revision:1,workspace:dir};let ms=Date.parse('2026-09-20T00:00:00Z');const options={rootDir:dir,getProject:()=>p,clockMs:()=>ms,nowIso:()=>new Date(ms).toISOString()};let s=new Service(options);try{const ids=[];for(let i=0;i<10;i++){ms+=60001;ids.push(s.createTrial(p.id,Buffer.from(JSON.stringify(envelope(model('maximum'),'maximum-static-'+i)))).id)}s.close();s=new Service(options);const page=s.listTrials(p.id);expect(page.trials).toHaveLength(10);expect(page.unavailable).toEqual([]);expect(page.nextOffset).toBeNull();expect(page.trials.every(x=>x.observationCount===256&&x.parameterCount===16&&x.baseObservationCount===128&&x.appendedObservationCount===128)).toBe(true);const a=s.getTrial(p.id,ids[0]);expect(a.result.steps).toHaveLength(128);expect(a.result.updatedFit.aprioriParameterCovariance).toHaveLength(16);s.getTrial(p.id,ids[1]);expect(()=>s.getTrial(p.id,ids[2])).toThrow('rate-limit')}finally{s.close();rmSync(dir,{recursive:true,force:true})}})
it.each(['updatedFit','baseQrState'])('recomputes and rejects coherent-hash forged %s at Runtime',target=>{const dir=mkdtempSync(join(tmpdir(),'static-forge-'));const p={id:'forge-static-project',revision:1,workspace:dir};const s=new Service({rootDir:dir,getProject:()=>p});let db:any;try{const summary=s.createTrial(p.id,Buffer.from(JSON.stringify(envelope())));db=new Database(join(dir,'survey-advanced-trials.sqlite3'));const row=db.prepare('SELECT * FROM advanced_trials WHERE id=?').get(summary.id);const r=JSON.parse(row.data_json);if(target==='updatedFit')r.result.updatedFit.parameters[0]+=1;else{r.result.baseQrState.upper[0][0]+=1;const {stateSha256,...state}=r.result.baseQrState;r.result.baseQrState.stateSha256=sha(JSON.stringify(state))}r.resultHash=digest(r.result);delete r.recordHash;r.recordHash=digest(r);row.record_hash=r.recordHash;row.data_json=JSON.stringify(r);const{storage_hash,request_bytes,declaration_bytes,...meta}=row;row.storage_hash=digest({...meta,request_bytes_sha256:sha(request_bytes),declaration_bytes_sha256:sha(declaration_bytes)});db.exec('DROP TRIGGER advanced_trials_no_update');const keys=Object.keys(row);db.prepare(`UPDATE advanced_trials SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).run(...keys.map(k=>row[k]),summary.id);expect(()=>s.getTrial(p.id,summary.id)).toThrow('integrity')}finally{db?.close();s.close();rmSync(dir,{recursive:true,force:true})}})
it('renderer independently binds QR hash and final base fingerprint after outer hashes are restamped',async()=>{for(const field of ['computedBaseFingerprint','finalFingerprint','baseQrState']){const f=fixture(),r=structuredClone(f.record);if(field==='baseQrState')r.result.baseQrState.upper[0][0]+=1;else r.result[field]='f'.repeat(64);r.resultHash=digest(r.result);const {recordHash,...unsigned}=r;r.recordHash=digest(unsigned);const summary={...f.summary,resultHash:r.resultHash,recordHash:r.recordHash};mock.mockResolvedValue({ok:true,status:200,body:JSON.stringify(r)} as any);await expect(readAdvancedTrial(f.binding,summary)).rejects.toMatchObject({reason:'invalid-response'})}})
