// @vitest-environment happy-dom
import {act,createElement} from '#repo/node_modules/react/index.js'
import {createRoot} from '#repo/node_modules/react-dom/client.js'
import {Buffer as NodeBuffer} from 'node:buffer'
import {webcrypto} from 'node:crypto'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {SurveyAdvancedModelWorkspace} from '#repo/src/renderer/src/components/engineering/SurveyAdvancedModelWorkspace.tsx'
import {fixture,model,envelope} from './fixtures'
import i18n from '#repo/src/renderer/src/i18n.ts'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
const request=vi.mocked(rendererRuntimeClient.runtimeRequest)
let root:any,host:HTMLDivElement
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(crypto,'subtle',{configurable:true,value:webcrypto.subtle});await i18n.changeLanguage('en');host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{vi.unstubAllGlobals();await act(async()=>root.unmount());host.remove();request.mockReset()})
const button=(key:string)=>[...host.querySelectorAll('button')].find(n=>n.textContent===i18n.t(key))!
async function click(n:HTMLElement){await act(async()=>n.click())}
async function settle(fn:()=>void){let e;for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,5))});try{fn();return}catch(x){e=x}}throw e}
async function restore(f:any){request.mockImplementation(async path=>({ok:true,status:200,body:path.includes('?')?JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null}):JSON.stringify(f.record)}));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await settle(()=>expect(host.textContent).toContain(i18n.t('advancedSavedRecord')))}
it.each(['en','zh'])('renders maximum 256/16/128 static append with complete covariance and visible model limits in %s',async language=>{await i18n.changeLanguage(language);const f=fixture(envelope(model('maximum')));vi.stubGlobal('Buffer',undefined);await restore(f);const result=host.querySelector(`[aria-label="${i18n.t('advancedStaticResults')}"]`)!;expect(result).not.toBeNull();const tables=result.querySelectorAll('table');expect(tables).toHaveLength(4);expect(tables[0].querySelectorAll('tbody tr')).toHaveLength(16);for(const table of [...tables].slice(1,3))expect(table.querySelectorAll('tbody td')).toHaveLength(256);expect(tables[3].querySelectorAll('tbody tr')).toHaveLength(128);expect(result.textContent).toContain(i18n.t('advancedStaticBoundary'));expect(result.textContent).toContain(i18n.t('advancedStaticAssumptions'));expect(result.textContent).toContain(i18n.t('advancedStaticComparisonBoundary'));expect(result.textContent).toContain(f.record.result.finalFingerprint);expect(result.textContent).not.toMatch(/\bNaN\b|\bInfinity\b|\bundefined\b/);expect(result.textContent).not.toMatch(/advancedStatic[A-Z]/);if(language==='en')expect(result.textContent).not.toMatch(/[㐀-鿿]/)})
it('shows prior covariance independently from posterior estimate and append/batch parameters',async()=>{const f=fixture();await restore(f);const result=host.querySelector(`[aria-label="${i18n.t('advancedStaticResults')}"]`)!;const tables=result.querySelectorAll('table');expect(tables[0].querySelectorAll('tbody td')[1].textContent).toBe(String(f.record.result.updatedFit.parameters[0]));expect(tables[2].querySelector('tbody td')!.textContent).toBe(String(f.record.result.updatedFit.aprioriParameterCovariance[0][0]));expect(result.textContent).toContain(i18n.t('advancedStaticPosterior',{sse:String(f.record.result.updatedFit.weightedResidualSumSquares),df:2,posterior:String(f.record.result.updatedFit.posteriorVarianceFactorEstimate)}));expect(result.textContent).toContain(i18n.t('advancedStaticBoundary'))})
it('stale old model remains unavailable with counts and no accepted table',async()=>{const f=fixture(envelope(model('stale')));await restore(f);const result=host.querySelector(`[aria-label="${i18n.t('advancedStaticResults')}"]`)!;expect(result.textContent).toContain(i18n.t('advancedStaticStale'));expect(result.querySelectorAll('table')).toHaveLength(0);expect(result.textContent).toContain(i18n.t('advancedStaticCounts',{base:2,appended:1,total:3}));expect(result.textContent).not.toContain(i18n.t('advancedStaticFinalFingerprint'))})
it('static Unicode export requires fresh server export and is suppressed after scope switch',async()=>{const f=fixture(),save=vi.fn().mockResolvedValue({ok:true,path:'/review/静态追加.json'});Object.assign(window,{workwise:{saveWorkspaceFileAs:save}});vi.stubGlobal('Buffer',undefined);await restore(f);await click(button('advancedExport'));await settle(()=>expect(save).toHaveBeenCalledOnce());const payload=save.mock.calls[0][0];expect(NodeBuffer.from(payload.dataBase64,'base64').toString('utf8')).toBe(JSON.stringify(f.record)+'\n');expect(payload.workspaceRoot).toBe(f.binding.workspaceRoot);expect(request.mock.calls.at(-1)[0]).toMatch(/\/export$/);await settle(()=>expect(host.textContent).toContain('/review/静态追加.json'));let release:any;request.mockImplementationOnce(()=>new Promise(r=>release=r));await click(button('advancedExport'));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,projectId:'changed'},runtimeReady:true})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(save).toHaveBeenCalledOnce();expect(host.textContent).not.toContain(f.summary.id)})
it.each(['workspace','revision','runtime'])('drops late static restore after %s changes',async key=>{const f=fixture();let release:any;request.mockImplementation(async path=>path.includes('?')?{ok:true,status:200,body:JSON.stringify({trials:[f.summary],unavailable:[],nextOffset:null})}:new Promise(r=>release=r));await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('advancedHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(i18n.t('advancedRestore')))!);await act(async()=>root.render(createElement(SurveyAdvancedModelWorkspace,{binding:{...f.binding,...(key==='workspace'?{workspaceRoot:'/changed'}:key==='revision'?{projectRevision:2}:{})},runtimeReady:key!=='runtime'})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(host.textContent).not.toContain(f.summary.id);expect(host.textContent).not.toContain(i18n.t('advancedSavedRecord'))})
