import '@xyflow/react/dist/style.css'
import { useCallback, useEffect, useMemo, useState, type ReactElement } from 'react'
import {
  Background, Controls, Handle, MiniMap, Position, ReactFlow, addEdge, applyEdgeChanges, applyNodeChanges,
  type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type NodeProps, type ReactFlowInstance
} from '@xyflow/react'
import { AlertTriangle, CheckCircle2, ChevronRight, Download, History, Loader2, Play, Save, Send, Square, TestTube2, Workflow } from 'lucide-react'
import { SidebarTitlebarToggleButton } from '../sidebar/SidebarPrimitives'
import { flowMatchesFilter, type FlowListFilter } from './flow-filter'

type PortType = 'string' | 'number' | 'boolean' | 'json' | 'table' | 'file' | 'document' | 'image' | 'agent_message'
type RegistryPort = { id: string; label: string; type: PortType; required: boolean; multiple: boolean }
type RegistryEntry = { type: string; category: string; label: string; inputs: RegistryPort[]; outputs: RegistryPort[]; available: boolean; disabledReason?: string; configurationRoute?: string }
type FlowNodeData = { label: string; nodeType: string; registry?: RegistryEntry; status?: string }
type FlowBinding = { kind: 'literal'; value: unknown } | { kind: 'variable'; variable: string } | { kind: 'port'; nodeId: string; portId: string }
type FlowDefinition = { schemaVersion: 1; id: string; name: string; description: string; revision: number; nodes: Array<{ id: string; type: string; label: string; position: { x: number; y: number }; bindings: Record<string, unknown>; config: Record<string, unknown>; policy: NodePolicy; disabled: boolean }>; edges: Array<{ id: string; sourceNodeId: string; sourcePortId: string; targetNodeId: string; targetPortId: string; conversionId?: string; branch: 'normal' | 'error' }>; variables: Record<string, unknown>; publishedVersionId?: string; createdAt: string; updatedAt: string }
type NodePolicy = { timeoutMs: number; retryAttempts: number; retryBackoffMs: number; errorBehavior: 'fail' | 'error_edge' | 'continue'; concurrencyLimit: number; resumable: boolean; breakpoint: boolean }
type ValidationIssue = { code: string; severity: 'error' | 'warning'; message: string; nodeId?: string }
type FlowRun = { id: string; status: string; startedAt: string; updatedAt: string }
type FlowNodeRun = { id: string; nodeId: string; attempt: number; status: string; input?: unknown; output?: unknown; error?: string }
type FlowRunDetails = { run: FlowRun; nodeRuns: FlowNodeRun[]; events: Array<{ id: string; type: string; nodeId?: string; payload: unknown; createdAt: string }> }

const PORT_COLORS: Record<PortType, string> = { string: '#2563eb', number: '#7c3aed', boolean: '#ca8a04', json: '#64748b', table: '#0891b2', file: '#475569', document: '#0f766e', image: '#db2777', agent_message: '#ea580c' }
const PORT_CONVERSIONS: Record<string, { from: PortType; to: PortType }> = { 'string-to-number': { from: 'string', to: 'number' }, 'string-to-boolean': { from: 'string', to: 'boolean' }, 'string-to-json': { from: 'string', to: 'json' }, 'table-to-json': { from: 'table', to: 'json' }, 'file-to-document': { from: 'file', to: 'document' }, 'image-to-file': { from: 'image', to: 'file' }, 'agent-message-to-string': { from: 'agent_message', to: 'string' } }
const DEFAULT_POLICY: NodePolicy = { timeoutMs: 120000, retryAttempts: 0, retryBackoffMs: 1000, errorBehavior: 'fail', concurrencyLimit: 1, resumable: false, breakpoint: false }
const MODEL_NODE_TYPES = new Set(['agent', 'subagent', 'classification', 'parameter_extraction', 'image_generation', 'speech_generation', 'music_generation', 'video_generation'])
const FLOW_NODE_TYPES = { workwise: FlowNodeCard }
const FLOW_NODE_WIDTH = 180
const FLOW_NODE_HEIGHT = 80
const NODE_CONFIG_FIELDS: Record<string, Array<{ key: string; label: string; kind?: 'number' | 'boolean' | 'json'; required?: boolean; placeholder?: string }>> = {
  schedule_trigger: [{ key: 'schedule', label: '计划表达式', required: true, placeholder: 'interval:15m / daily:09:00' }, { key: 'timezone', label: '时区', placeholder: 'Asia/Shanghai' }],
  webhook_trigger: [{ key: 'credentialRef', label: 'Webhook 密钥引用', required: true }],
  agent: [{ key: 'prompt', label: '系统提示词', required: true }], subagent: [{ key: 'prompt', label: '委派提示词', required: true }],
  knowledge_retrieval: [{ key: 'attachmentId', label: '附件 ID' }, { key: 'query', label: '检索词' }, { key: 'limit', label: '结果上限', kind: 'number' }],
  classification: [{ key: 'categories', label: '分类列表(JSON)', kind: 'json', required: true }, { key: 'prompt', label: '分类说明' }],
  parameter_extraction: [{ key: 'schema', label: '参数 Schema(JSON)', kind: 'json', required: true }, { key: 'prompt', label: '抽取说明' }],
  http: [{ key: 'url', label: 'URL', required: true, placeholder: 'https://...' }, { key: 'method', label: '方法', placeholder: 'GET' }, { key: 'headers', label: '请求头(JSON)', kind: 'json' }, { key: 'body', label: '请求体(JSON)', kind: 'json' }, { key: 'allowLoopback', label: '允许本机 HTTP', kind: 'boolean' }],
  restricted_code: [{ key: 'source', label: '受限代码', required: true }], condition: [{ key: 'path', label: '字段路径' }, { key: 'operator', label: '条件操作符', placeholder: 'equals / exists / truthy' }, { key: 'value', label: '比较值(JSON)', kind: 'json' }],
  switch: [{ key: 'path', label: '字段路径' }, { key: 'cases', label: '分支(JSON)', kind: 'json', required: true }, { key: 'defaultBranch', label: '默认分支' }],
  loop: [{ key: 'maxIterations', label: '最大循环次数', kind: 'number', required: true }],
  human_approval: [{ key: 'summary', label: '审批说明' }], alert_confirmation: [{ key: 'summary', label: '告警说明' }],
  docx_output: [{ key: 'outputPath', label: '输出路径', required: true }], xlsx_output: [{ key: 'outputPath', label: '输出路径', required: true }], pdf_output: [{ key: 'outputPath', label: '输出路径', required: true }], pptx_output: [{ key: 'outputPath', label: '输出路径', required: true }],
  run_flow: [{ key: 'flowId', label: '目标 Flow ID', required: true }]
}

export function createStarterFlowInput(id: string): Omit<FlowDefinition, 'revision' | 'createdAt' | 'updatedAt' | 'publishedVersionId'> {
  const triggerId = `manual_${crypto.randomUUID().slice(0, 8)}`
  const agentId = `agent_${crypto.randomUUID().slice(0, 8)}`
  return {
    schemaVersion: 1,
    id,
    name: '我的第一个 Flow',
    description: '手动触发后由 Agent 处理输入。选择节点可配置参数和单节点测试。',
    nodes: [
      {
        id: triggerId,
        type: 'manual_trigger',
        label: '手动触发',
        position: { x: 120, y: 180 },
        bindings: {},
        config: {},
        policy: { ...DEFAULT_POLICY },
        disabled: false
      },
      {
        id: agentId,
        type: 'agent',
        label: 'Agent 处理',
        position: { x: 420, y: 180 },
        bindings: {},
        config: { prompt: '请根据 Flow 输入完成任务，并返回清晰、可核验的结果。' },
        policy: { ...DEFAULT_POLICY, retryAttempts: 1, resumable: true },
        disabled: false
      }
    ],
    edges: [{
      id: `edge_${crypto.randomUUID().slice(0, 8)}`,
      sourceNodeId: triggerId,
      sourcePortId: 'output',
      targetNodeId: agentId,
      targetPortId: 'input',
      branch: 'normal'
    }],
    variables: {}
  }
}

export function FlowWorkspaceView({ leftSidebarCollapsed, onToggleLeftSidebar, filter }: { leftSidebarCollapsed: boolean; onToggleLeftSidebar: () => void; filter: FlowListFilter }): ReactElement {
  const [flows, setFlows] = useState<FlowDefinition[]>([]); const [registry, setRegistry] = useState<RegistryEntry[]>([])
  const [activeId, setActiveId] = useState<string | null>(null); const [draft, setDraft] = useState<FlowDefinition | null>(null)
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null); const [issues, setIssues] = useState<ValidationIssue[]>([])
  const [runs, setRuns] = useState<FlowRun[]>([]); const [mockInput, setMockInput] = useState('{}'); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null); const [runDetails, setRunDetails] = useState<FlowRunDetails | null>(null)
  const [flowInstance, setFlowInstance] = useState<ReactFlowInstance<Node<FlowNodeData>, Edge> | null>(null)

  const visibleFlows = useMemo(() => flows.filter((flow) => flowMatchesFilter(flow, filter)), [filter, flows])
  const load = useCallback(async () => { setBusy('loading'); try { const result = await runtimeJson<{ flows: FlowDefinition[]; registry: RegistryEntry[] }>('/v1/flows'); setFlows(result.flows); setRegistry(result.registry); const filtered = result.flows.filter((flow) => flowMatchesFilter(flow, filter)); const selected = filtered.find((flow) => flow.id === activeId) ?? filtered[0] ?? null; setActiveId(selected?.id ?? null); setDraft(selected); setError(null) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }, [activeId, filter])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (!activeId) { setRuns([]); return } void runtimeJson<{ runs: FlowRun[] }>(`/v1/flows/${encodeURIComponent(activeId)}/history`).then((value) => setRuns(value.runs)).catch(() => setRuns([])) }, [activeId])
  useEffect(() => { if (!selectedRunId) { setRunDetails(null); return } void runtimeJson<FlowRunDetails>(`/v1/flow-runs/${selectedRunId}`).then(setRunDetails).catch((reason) => setError(message(reason))) }, [selectedRunId])

  const nodes = useMemo<Node<FlowNodeData>[]>(() => (draft?.nodes ?? []).map((node) => ({
    id: node.id,
    type: 'workwise',
    position: node.position,
    width: FLOW_NODE_WIDTH,
    height: FLOW_NODE_HEIGHT,
    data: { label: node.label, nodeType: node.type, registry: registry.find((entry) => entry.type === node.type) },
    selected: node.id === selectedNodeId
  })), [draft, registry, selectedNodeId])
  const edges = useMemo<Edge[]>(() => (draft?.edges ?? []).map((edge) => ({ id: edge.id, source: edge.sourceNodeId, sourceHandle: edge.sourcePortId, target: edge.targetNodeId, targetHandle: edge.targetPortId, animated: false, style: { stroke: '#94a3b8' } })), [draft])
  const selectedNode = draft?.nodes.find((node) => node.id === selectedNodeId) ?? null

  useEffect(() => {
    if (!flowInstance || !draft || nodes.length === 0) return
    const frame = window.requestAnimationFrame(() => {
      void flowInstance.fitView({ padding: 0.2, minZoom: 0.4, maxZoom: 1.2, duration: 0 })
    })
    return () => window.cancelAnimationFrame(frame)
  }, [draft?.id, flowInstance, nodes.length])

  const onNodesChange = (changes: NodeChange<Node<FlowNodeData>>[]) => { if (!draft) return; const changed = applyNodeChanges(changes, nodes); setDraft({ ...draft, nodes: draft.nodes.map((node) => ({ ...node, position: changed.find((item) => item.id === node.id)?.position ?? node.position })) }) }
  const onEdgesChange = (changes: EdgeChange<Edge>[]) => { if (!draft) return; const changed = applyEdgeChanges(changes, edges); setDraft({ ...draft, edges: changed.map((edge) => ({ id: edge.id, sourceNodeId: edge.source, sourcePortId: edge.sourceHandle ?? 'output', targetNodeId: edge.target, targetPortId: edge.targetHandle ?? 'input', branch: 'normal' })) }) }
  const onConnect = (connection: Connection) => { if (!draft || !connection.source || !connection.target || !connection.sourceHandle || !connection.targetHandle) return; const source = registry.find((entry) => entry.type === draft.nodes.find((node) => node.id === connection.source)?.type)?.outputs.find((port) => port.id === connection.sourceHandle); const target = registry.find((entry) => entry.type === draft.nodes.find((node) => node.id === connection.target)?.type)?.inputs.find((port) => port.id === connection.targetHandle); const compatibility = source && target ? flowPortCompatibility(source.type, target.type) : null; if (!compatibility) { setError(`端口类型不兼容：${source?.type ?? '?'} → ${target?.type ?? '?'}`); return } const next = addEdge(connection, edges); const item = next.at(-1)!; if (!draft) return; setDraft({ ...draft, edges: [...draft.edges, { id: item.id, sourceNodeId: connection.source, sourcePortId: connection.sourceHandle, targetNodeId: connection.target, targetPortId: connection.targetHandle, ...(compatibility.conversionId ? { conversionId: compatibility.conversionId } : {}), branch: 'normal' }] }); setError(null) }
  const addNode = (entry: RegistryEntry) => { if (!draft || !entry.available) return; const id = `${entry.type}_${crypto.randomUUID().slice(0, 8)}`; const next = { id, type: entry.type, label: entry.label, position: { x: 180 + draft.nodes.length * 24, y: 100 + draft.nodes.length * 20 }, bindings: {}, config: entry.type === 'loop' ? { maxIterations: 10 } : {}, policy: { ...DEFAULT_POLICY }, disabled: false }; setDraft({ ...draft, nodes: [...draft.nodes, next] }); setSelectedNodeId(id) }
  const createFlow = async () => { setBusy('create'); try { const id = `flow_${crypto.randomUUID()}`; const value = await runtimeJson<{ flow: FlowDefinition }>('/v1/flows', 'POST', createStarterFlowInput(id)); setFlows((current) => [value.flow, ...current]); setActiveId(id); setDraft(value.flow); setSelectedNodeId(value.flow.nodes.find((node) => node.type === 'agent')?.id ?? null); setIssues([]); setError(null) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const save = async () => { if (!draft) return; setBusy('save'); try { const value = await runtimeJson<{ flow: FlowDefinition }>(`/v1/flows/${draft.id}`, 'PUT', { definition: draft, expectedRevision: draft.revision }); setDraft(value.flow); setFlows((current) => current.map((flow) => flow.id === value.flow.id ? value.flow : flow)); setError(null) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const validate = async () => { if (!draft) return false; const result = await runtimeJson<{ valid: boolean; issues: ValidationIssue[] }>('/v1/flows/validate', 'POST', { definition: draft }); setIssues(result.issues); return result.valid }
  const publish = async () => { if (!draft) return; setBusy('publish'); try { await save(); const result = await runtimeJson<{ published: boolean; validation: { issues: ValidationIssue[] } }>('/v1/flows/publish', 'POST', { id: draft.id }); setIssues(result.validation.issues); if (!result.published) throw new Error('发布校验未通过') } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const run = async () => { if (!draft) return; setBusy('run'); try { const input = JSON.parse(mockInput); const result = await runtimeJson<{ run: FlowRun }>('/v1/flows/run', 'POST', { flowId: draft.id, input, invocationStack: [] }); setRuns((current) => [result.run, ...current.filter((item) => item.id !== result.run.id)]) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const testNode = async () => { if (!draft || !selectedNodeId) return; setBusy('test'); try { await runtimeJson('/v1/flows/test-node', 'POST', { definition: draft, nodeId: selectedNodeId, mockInput: JSON.parse(mockInput) }) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const cancelRun = async () => { const active = runs.find((item) => ['queued', 'running', 'waiting_approval', 'paused', 'interrupted'].includes(item.status)); if (!active) return; setBusy('cancel'); try { await runtimeJson(`/v1/flow-runs/${active.id}/cancel`, 'POST', {}); setRuns((current) => current.map((item) => item.id === active.id ? { ...item, status: 'cancelled', updatedAt: new Date().toISOString() } : item)) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const exportRedacted = async () => { if (!draft) return; setBusy('export'); try { const result = await runtimeJson<{ flow: unknown }>(`/v1/flows/${draft.id}/export`); const json = `${JSON.stringify(result.flow, null, 2)}\n`; const saved = await window.workwise.saveWorkspaceFileAs({ suggestedName: `${safeFileName(draft.name)}.workwise-flow.json`, dataBase64: utf8Base64(json), mimeType: 'application/json' }); if (!saved.ok && !saved.canceled) throw new Error(saved.message) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }
  const runAction = async (action: 'resume' | 'retry' | 'approve' | 'reject', nodeId?: string) => { if (!selectedRunId) return; setBusy(action); try { if (action === 'approve' || action === 'reject') await runtimeJson('/v1/flow-runs/decision', 'POST', { runId: selectedRunId, nodeId, decision: action }); else await runtimeJson(`/v1/flow-runs/${selectedRunId}/${action}`, 'POST', action === 'retry' ? { nodeId } : {}); const details = await runtimeJson<FlowRunDetails>(`/v1/flow-runs/${selectedRunId}`); setRunDetails(details); setRuns((current) => current.map((item) => item.id === details.run.id ? details.run : item)) } catch (reason) { setError(message(reason)) } finally { setBusy(null) } }

  return <div className="flex h-full min-h-0 flex-col bg-[#f8fafc] text-[#1e293b] dark:bg-ds-main dark:text-white">
    <header className="ds-drag flex h-14 shrink-0 items-center gap-3 border-b border-[#e2e8f0] bg-white px-4 dark:border-ds-border dark:bg-ds-card">
      {leftSidebarCollapsed ? <SidebarTitlebarToggleButton onClick={onToggleLeftSidebar} title="展开侧边栏" ariaLabel="展开侧边栏" /> : null}
      <Workflow className="h-5 w-5 text-blue-600" /><h1 className="text-[16px] font-semibold">WorkWise Flow</h1><span className="rounded bg-blue-50 px-2 py-0.5 text-[11px] font-medium text-blue-600 dark:bg-blue-400/10 dark:text-blue-300">Preview</span>
      {filter === 'scheduled' ? <span className="rounded bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-700">定时流程</span> : null}<select className="ds-no-drag ml-3 rounded-lg border border-[#e2e8f0] bg-white px-3 py-1.5 text-[13px] dark:border-ds-border dark:bg-ds-main" value={activeId ?? ''} onChange={(event) => { const flow = visibleFlows.find((item) => item.id === event.target.value) ?? null; setActiveId(flow?.id ?? null); setDraft(flow) }}><option value="">选择流程</option>{visibleFlows.map((flow) => <option key={flow.id} value={flow.id}>{flow.name}</option>)}</select>
      <button className="ds-no-drag rounded-lg border border-[#e2e8f0] px-3 py-1.5 text-[13px] hover:bg-slate-50 dark:border-ds-border" onClick={() => void createFlow()}>新建</button>
      <div className="ml-auto flex gap-2">{busy ? <Loader2 className="h-4 w-4 animate-spin text-blue-600" /> : null}<Action icon={<Save />} label="保存" onClick={() => void save()} /><Action icon={<CheckCircle2 />} label="校验" onClick={() => void validate()} /><Action icon={<Download />} label="脱敏导出" onClick={() => void exportRedacted()} /><Action icon={<Send />} label="发布" primary onClick={() => void publish()} /><Action icon={<Play />} label="运行" primary onClick={() => void run()} />{runs.some((item) => ['queued', 'running', 'waiting_approval', 'paused', 'interrupted'].includes(item.status)) ? <Action icon={<Square />} label="取消" onClick={() => void cancelRun()} /> : null}</div>
    </header>
    {error ? <div className="flex items-center gap-2 border-b border-red-200 bg-red-50 px-4 py-2 text-[12px] text-red-700"><AlertTriangle className="h-4 w-4" />{error}</div> : null}
    <div className="grid min-h-0 flex-1 grid-cols-1 grid-rows-[auto_minmax(320px,1fr)_auto] lg:grid-cols-[220px_minmax(360px,1fr)_320px] lg:grid-rows-1">
      <aside className="max-h-44 overflow-y-auto border-b border-r border-[#e2e8f0] bg-white p-3 dark:border-ds-border dark:bg-ds-card lg:max-h-none"><div className="mb-3 text-[12px] font-semibold text-[#64748b]">节点目录</div>{registry.length === 0 && busy === 'loading' ? <LoadingState label="正在加载节点目录" /> : groupRegistry(registry).map(([category, entries]) => <section key={category} className="mb-4"><div className="mb-1.5 text-[11px] uppercase tracking-wide text-[#94a3b8]">{category}</div><div className="space-y-1">{entries.map((entry) => <button key={entry.type} disabled={!entry.available || !draft} title={flowRegistryAvailabilityLabel(entry)} aria-label={`${entry.label}。${flowRegistryAvailabilityLabel(entry)}`} onClick={() => addNode(entry)} className="flex w-full items-center gap-2 rounded-lg border border-transparent px-2 py-2 text-left text-[12px] hover:border-blue-100 hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-45 dark:hover:bg-blue-400/10"><ChevronRight className="h-3.5 w-3.5" /><span className="truncate">{entry.label}</span></button>)}</div></section>)}</aside>
      <main className="relative min-h-[320px] min-w-0 bg-[radial-gradient(circle,#cbd5e1_1px,transparent_1px)] [background-size:20px_20px]">{busy === 'loading' && !draft ? <LoadingState label="正在加载 Flow" /> : !draft ? <EmptyState onCreate={() => void createFlow()} /> : <ReactFlow key={draft.id} aria-label="Flow 画布" className="h-full w-full" style={{ width: '100%', height: '100%' }} nodes={nodes} edges={edges} nodeTypes={FLOW_NODE_TYPES} onInit={setFlowInstance} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_, node) => setSelectedNodeId(node.id)} fitView fitViewOptions={{ padding: 0.2, minZoom: 0.4, maxZoom: 1.2 }} deleteKeyCode={['Backspace', 'Delete']} selectionOnDrag multiSelectionKeyCode="Shift"><MiniMap pannable zoomable nodeColor="#2563eb" /><Controls /><Background gap={20} size={1} color="transparent" /></ReactFlow>}</main>
      <aside className="min-h-0 overflow-y-auto border-l border-[#e2e8f0] bg-white p-4 dark:border-ds-border dark:bg-ds-card"><FlowNodeInspector node={selectedNode} entry={selectedNode ? registry.find((item) => item.type === selectedNode.type) : undefined} allNodes={draft?.nodes ?? []} registry={registry} variables={draft?.variables ?? {}} onChange={(next) => draft && setDraft({ ...draft, nodes: draft.nodes.map((item) => item.id === next.id ? next : item) })} mockInput={mockInput} onMockInput={setMockInput} onTest={() => void testNode()} busy={busy === 'test'} /><div className="my-5 border-t border-[#e2e8f0] dark:border-ds-border" /><div className="mb-2 flex items-center gap-2 text-[13px] font-semibold"><History className="h-4 w-4" />运行历史</div><div className="space-y-2">{runs.slice(0, 20).map((runItem) => <button type="button" onClick={() => setSelectedRunId(runItem.id)} key={runItem.id} className={`w-full rounded-lg border p-2 text-left text-[11px] dark:border-ds-border ${selectedRunId === runItem.id ? 'border-blue-400 bg-blue-50' : 'border-[#e2e8f0]'}`}><div className="flex items-center justify-between"><span className="truncate font-mono">{runItem.id.slice(-10)}</span><Status value={runItem.status} /></div><div className="mt-1 text-[#94a3b8]">{new Date(runItem.updatedAt).toLocaleString()}</div></button>)}</div>{runDetails ? <RunDetailsPanel details={runDetails} onAction={(action, nodeId) => void runAction(action, nodeId)} busy={busy !== null} /> : null}{issues.length ? <><div className="my-5 border-t border-[#e2e8f0]" /><div className="mb-2 text-[13px] font-semibold">校验问题</div>{issues.map((issue, index) => <div key={`${issue.code}-${index}`} className="mb-2 rounded-lg bg-red-50 p-2 text-[11px] text-red-700">{issue.message}</div>)}</> : null}</aside>
    </div>
  </div>
}

function FlowNodeCard({ data, selected }: NodeProps<Node<FlowNodeData>>): ReactElement { const entry = data.registry; return <div role="group" aria-label={`${data.label}，${data.nodeType} 节点`} className={`min-w-[180px] rounded-xl border bg-white shadow-sm ${selected ? 'border-blue-500 ring-2 ring-blue-100' : 'border-[#e2e8f0]'}`}><div className="border-b border-[#e2e8f0] px-3 py-2"><div className="text-[12px] font-semibold">{data.label}</div><div className="text-[10px] text-[#94a3b8]">{data.nodeType}</div></div><div className="relative flex min-h-8 justify-between gap-4 px-2 py-2">{entry?.inputs.map((port, index) => <div key={port.id} className="relative text-[9px] text-[#64748b]"><Handle id={port.id} type="target" position={Position.Left} aria-label={`输入端口 ${port.label} ${port.type}`} style={{ top: 12 + index * 18, background: PORT_COLORS[port.type] }} />{port.label}</div>)}<div className="ml-auto">{entry?.outputs.map((port, index) => <div key={port.id} className="relative text-right text-[9px] text-[#64748b]">{port.label}<Handle id={port.id} type="source" position={Position.Right} aria-label={`输出端口 ${port.label} ${port.type}`} style={{ top: 12 + index * 18, background: PORT_COLORS[port.type] }} /></div>)}</div></div></div> }
export function FlowNodeInspector({ node, entry, allNodes, registry, variables, onChange, mockInput, onMockInput, onTest, busy }: { node: FlowDefinition['nodes'][number] | null; entry?: RegistryEntry; allNodes: FlowDefinition['nodes']; registry: RegistryEntry[]; variables: Record<string, unknown>; onChange: (node: FlowDefinition['nodes'][number]) => void; mockInput: string; onMockInput: (value: string) => void; onTest: () => void; busy: boolean }): ReactElement {
  if (!node) return <div className="py-10 text-center text-[12px] text-[#94a3b8]">选择节点后配置参数</div>
  const policy = node.policy; const bindings = node.bindings as Record<string, FlowBinding>
  const changePolicy = (patch: Partial<NodePolicy>) => onChange({ ...node, policy: { ...policy, ...patch } })
  const changeConfig = (key: string, value: unknown) => onChange({ ...node, config: { ...node.config, [key]: value } })
  const changeBinding = (portId: string, binding: FlowBinding) => onChange({ ...node, bindings: { ...node.bindings, [portId]: binding } })
  const portOptions = allNodes.filter((item) => item.id !== node.id).flatMap((item) => (registry.find((candidate) => candidate.type === item.type)?.outputs ?? []).map((port) => ({ value: `${item.id}:${port.id}`, label: `${item.label} · ${port.label}` })))
  return <div><div className="mb-3 text-[13px] font-semibold">节点配置</div><Field label="名称"><input value={node.label} onChange={(event) => onChange({ ...node, label: event.target.value })} /></Field>
    {entry?.inputs.length ? <section className="mt-4"><div className="text-[11px] font-semibold text-[#475569]">输入绑定</div>{entry.inputs.map((port) => { const binding = bindings[port.id] ?? { kind: 'literal', value: '' }; return <div key={port.id} className="mt-2 rounded-lg border border-[#e2e8f0] p-2"><div className="flex items-center justify-between text-[11px]"><span>{port.label}{port.required ? ' *' : ''}</span><span className="text-[9px] text-[#94a3b8]">{port.type}</span></div><select className="mt-1 w-full rounded border border-[#e2e8f0] px-2 py-1 text-[11px]" value={binding.kind} onChange={(event) => changeBinding(port.id, event.target.value === 'variable' ? { kind: 'variable', variable: Object.keys(variables)[0] ?? '' } : event.target.value === 'port' ? { kind: 'port', nodeId: '', portId: '' } : { kind: 'literal', value: '' })}><option value="literal">常量</option><option value="variable">Flow 变量</option><option value="port">节点输出</option></select>{binding.kind === 'literal' ? <textarea className="mt-1 w-full rounded border border-[#e2e8f0] p-1.5 font-mono text-[10px]" value={formatConfigValue(binding.value)} onChange={(event) => changeBinding(port.id, { kind: 'literal', value: parseConfigValue(event.target.value) })} /> : binding.kind === 'variable' ? <select className="mt-1 w-full rounded border border-[#e2e8f0] px-2 py-1 text-[11px]" value={binding.variable} onChange={(event) => changeBinding(port.id, { kind: 'variable', variable: event.target.value })}><option value="">选择变量</option>{Object.keys(variables).map((key) => <option key={key}>{key}</option>)}</select> : <select className="mt-1 w-full rounded border border-[#e2e8f0] px-2 py-1 text-[11px]" value={`${binding.nodeId}:${binding.portId}`} onChange={(event) => { const [nodeId, portId] = event.target.value.split(':'); changeBinding(port.id, { kind: 'port', nodeId: nodeId ?? '', portId: portId ?? '' }) }}><option value=":">选择节点输出</option>{portOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>}</div> })}</section> : null}
    {MODEL_NODE_TYPES.has(node.type) ? <div className="grid grid-cols-2 gap-2"><Field label="提供商"><input value={String(node.config.provider ?? '')} onChange={(event) => changeConfig('provider', event.target.value)} placeholder="默认" /></Field><Field label="模型"><input value={String(node.config.model ?? '')} onChange={(event) => changeConfig('model', event.target.value)} placeholder="默认模型" /></Field></div> : null}
    {(NODE_CONFIG_FIELDS[node.type] ?? []).map((field) => <Field key={field.key} label={`${field.label}${field.required ? ' *' : ''}`}>{field.kind === 'boolean' ? <input type="checkbox" checked={node.config[field.key] === true} onChange={(event) => changeConfig(field.key, event.target.checked)} /> : field.kind === 'json' ? <textarea rows={3} className="font-mono" value={formatConfigValue(node.config[field.key])} onChange={(event) => changeConfig(field.key, parseConfigValue(event.target.value))} placeholder={field.placeholder} /> : <input type={field.kind === 'number' ? 'number' : 'text'} value={String(node.config[field.key] ?? '')} onChange={(event) => changeConfig(field.key, field.kind === 'number' ? Number(event.target.value) : event.target.value)} placeholder={field.placeholder} />}</Field>)}
    <div className="mt-4 text-[11px] font-semibold text-[#475569]">执行策略</div><div className="grid grid-cols-2 gap-2"><Field label="超时(ms)"><input type="number" min={100} max={3600000} value={policy.timeoutMs} onChange={(event) => changePolicy({ timeoutMs: Number(event.target.value) })} /></Field><Field label="重试次数"><input type="number" min={0} max={10} value={policy.retryAttempts} onChange={(event) => changePolicy({ retryAttempts: Number(event.target.value) })} /></Field><Field label="退避(ms)"><input type="number" min={0} max={300000} value={policy.retryBackoffMs} onChange={(event) => changePolicy({ retryBackoffMs: Number(event.target.value) })} /></Field><Field label="并发限制"><input type="number" min={1} max={64} value={policy.concurrencyLimit} onChange={(event) => changePolicy({ concurrencyLimit: Number(event.target.value) })} /></Field></div><Field label="错误处理"><select className="w-full rounded-lg border border-[#e2e8f0] px-2 py-1.5" value={policy.errorBehavior} onChange={(event) => changePolicy({ errorBehavior: event.target.value as NodePolicy['errorBehavior'] })}><option value="fail">失败并停止</option><option value="error_edge">错误分支</option><option value="continue">记录后继续</option></select></Field><label className="mt-2 flex items-center gap-2 text-[11px]"><input type="checkbox" checked={policy.resumable} onChange={(event) => changePolicy({ resumable: event.target.checked })} />可恢复</label><label className="mt-2 flex items-center gap-2 text-[11px]"><input type="checkbox" checked={policy.breakpoint} onChange={(event) => changePolicy({ breakpoint: event.target.checked })} />断点</label><Field label="Mock JSON"><textarea rows={5} value={mockInput} onChange={(event) => onMockInput(event.target.value)} className="font-mono" /></Field><button onClick={onTest} disabled={busy} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-[12px] text-blue-700 disabled:opacity-50"><TestTube2 className="h-4 w-4" />单节点测试</button></div>
}
function formatConfigValue(value: unknown): string { if (value === undefined) return ''; return typeof value === 'string' ? value : JSON.stringify(value, null, 2) }
function parseConfigValue(value: string): unknown { const trimmed = value.trim(); if (!trimmed) return ''; try { return JSON.parse(trimmed) } catch { return value } }
export function RunDetailsPanel({ details, onAction, busy }: { details: FlowRunDetails; onAction: (action: 'resume' | 'retry' | 'approve' | 'reject', nodeId?: string) => void; busy: boolean }): ReactElement { return <section className="mt-4 border-t border-[#e2e8f0] pt-3"><div className="mb-2 flex items-center justify-between text-[12px] font-semibold"><span>运行详情</span><Status value={details.run.status} /></div>{['interrupted', 'paused', 'failed'].includes(details.run.status) ? <button disabled={busy} onClick={() => onAction('resume')} className="mb-2 rounded bg-blue-50 px-2 py-1 text-[10px] text-blue-700">从检查点恢复</button> : null}<div className="space-y-2">{details.nodeRuns.map((nodeRun) => <details key={nodeRun.id} className="rounded-lg border border-[#e2e8f0] p-2 text-[10px]"><summary className="flex cursor-pointer items-center justify-between"><span>{nodeRun.nodeId} · #{nodeRun.attempt}</span><Status value={nodeRun.status} /></summary>{nodeRun.input !== undefined ? <JsonBlock label="输入" value={nodeRun.input} /> : null}{nodeRun.output !== undefined ? <JsonBlock label="输出" value={nodeRun.output} /> : null}{nodeRun.error ? <div className="mt-2 rounded bg-red-50 p-2 text-red-700">{nodeRun.error}</div> : null}<div className="mt-2 flex gap-1">{nodeRun.status === 'waiting_approval' ? <><button disabled={busy} onClick={() => onAction('approve', nodeRun.nodeId)} className="rounded bg-green-50 px-2 py-1 text-green-700">批准</button><button disabled={busy} onClick={() => onAction('reject', nodeRun.nodeId)} className="rounded bg-red-50 px-2 py-1 text-red-700">拒绝</button></> : null}{nodeRun.status === 'failed' ? <button disabled={busy} onClick={() => onAction('retry', nodeRun.nodeId)} className="rounded bg-blue-50 px-2 py-1 text-blue-700">从此节点重试</button> : null}</div></details>)}</div><details className="mt-2 text-[10px]"><summary className="cursor-pointer text-[#64748b]">事件记录 ({details.events.length})</summary><pre className="mt-1 max-h-40 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-2">{JSON.stringify(details.events, null, 2)}</pre></details></section> }
function JsonBlock({ label, value }: { label: string; value: unknown }): ReactElement { return <div className="mt-2"><div className="text-[#64748b]">{label}</div><pre className="max-h-32 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-2">{JSON.stringify(value, null, 2)}</pre></div> }
function safeFileName(value: string): string { return value.trim().replace(/[\\/:*?"<>|]/g, '_').slice(0, 100) || 'flow' }
function utf8Base64(value: string): string { const bytes = new TextEncoder().encode(value); let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary) }
export function flowPortCompatibility(from: PortType, to: PortType): { conversionId?: string } | null { if (from === to) return {}; const conversion = Object.entries(PORT_CONVERSIONS).find(([, value]) => value.from === from && value.to === to); return conversion ? { conversionId: conversion[0] } : null }
export function flowRegistryAvailabilityLabel(entry: RegistryEntry): string { if (entry.available) return '可用'; return [entry.disabledReason ?? '能力未配置', entry.configurationRoute ? `配置入口：${entry.configurationRoute}` : ''].filter(Boolean).join('；') }
function Field({ label, children }: { label: string; children: ReactElement }): ReactElement { return <label className="mt-2 block text-[11px] text-[#64748b]"><span className="mb-1 block">{label}</span><span className="[&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#e2e8f0] [&>input]:px-2 [&>input]:py-1.5 [&>textarea]:w-full [&>textarea]:rounded-lg [&>textarea]:border [&>textarea]:border-[#e2e8f0] [&>textarea]:p-2">{children}</span></label> }
function Action({ icon, label, onClick, primary }: { icon: ReactElement; label: string; onClick: () => void; primary?: boolean }): ReactElement { return <button onClick={onClick} className={`ds-no-drag flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[12px] ${primary ? 'bg-blue-600 text-white hover:bg-blue-700' : 'border border-[#e2e8f0] bg-white hover:bg-slate-50 dark:border-ds-border dark:bg-ds-main'}`}>{<span className="[&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span>}{label}</button> }
export function flowStatusClass(value: string): string { if (value === 'succeeded') return 'bg-green-100 text-green-700'; if (value === 'failed') return 'bg-red-100 text-red-700'; if (value === 'paused') return 'bg-yellow-100 text-yellow-700'; if (value.includes('approval') || value === 'interrupted') return 'bg-orange-100 text-orange-700'; if (value === 'cancelled' || value === 'skipped') return 'bg-slate-100 text-slate-600'; return 'bg-blue-100 text-blue-700' }
function Status({ value }: { value: string }): ReactElement { return <span className={`rounded px-1.5 py-0.5 ${flowStatusClass(value)}`}>{value}</span> }
function LoadingState({ label }: { label: string }): ReactElement { return <div className="flex h-full min-h-24 items-center justify-center gap-2 text-[12px] text-blue-600"><Loader2 className="h-4 w-4 animate-spin" />{label}</div> }
function EmptyState({ onCreate }: { onCreate: () => void }): ReactElement { return <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 p-6 text-center"><Workflow className="h-9 w-9 text-[#94a3b8]" /><div><div className="text-[14px] font-semibold">还没有 Flow</div><div className="mt-1 text-[12px] text-[#64748b]">新建流程后，从左侧目录添加触发器与执行节点。</div></div><button onClick={onCreate} className="rounded-lg bg-blue-600 px-3 py-2 text-[12px] text-white">新建 Flow</button></div> }
async function runtimeJson<T = unknown>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await window.workwise.runtimeRequest(path, method, body === undefined ? undefined : JSON.stringify(body)); if (!response.ok) { let value: { message?: string } = {}; try { value = JSON.parse(response.body) } catch { /* empty */ } throw new Error(value.message ?? `Runtime request failed (${response.status})`) } return JSON.parse(response.body) as T }
function message(value: unknown): string { return value instanceof Error ? value.message : String(value) }
function groupRegistry(registry: RegistryEntry[]): Array<[string, RegistryEntry[]]> { const groups = new Map<string, RegistryEntry[]>(); for (const entry of registry) groups.set(entry.category, [...(groups.get(entry.category) ?? []), entry]); return [...groups.entries()] }
