import {describe,expect,it} from 'vitest'
import {runtimeRequestPayloadSchema as schema} from './app-ipc-schemas'
const base='/v1/engineering/projects/p/quality-assessments',plans='/v1/engineering/projects/p/quality-assessment-plans'
const plan={schemaVersion:1,acknowledged:true,expectedProjectRevision:1,idempotencyKey:'test-key-1',retentionPlanId:'retention-p',retentionRecordId:'retention-r',samplingRunId:'run',productProfileId:'planar-control-point',basisStatement:'Declared only',unitMaterials:[{unitId:'u',requirements:[{reference:'ref',retentionCheckId:'evidence:x',memberId:'output-1',locatorStatement:'Declared location'}]}]}
const request={schemaVersion:1,acknowledged:true,expectedProjectRevision:1,idempotencyKey:'test-key-2',assessmentPlanId:'plan',expectedPlanHash:'a'.repeat(64),unitScores:[]}
describe('assessment desktop IPC',()=>{
 it('allows only explicit plan, detail, reverify, export and bounded list',()=>{for(const p of [{path:plans,method:'POST',body:JSON.stringify(plan)},{path:base,method:'POST',body:JSON.stringify(request)},{path:`${base}?limit=10&offset=128`},{path:`${plans}/p`},{path:`${base}/r`},{path:`${base}/r/reverify`,method:'POST',body:'{}'},{path:`${base}/r/export`}])expect(schema.safeParse(p).success).toBe(true)})
 it('rejects forged approval, unknown fields, duplicate JSON and route confusion',()=>{for(const p of [{path:plans,method:'POST',body:JSON.stringify({...plan,approved:true})},{path:base,method:'POST',body:JSON.stringify({...request,result:{}})},{path:base,method:'POST',body:JSON.stringify(request).replace('"schemaVersion":1','"schemaVersion":1,"schema\\u0056ersion":1')},{path:`${plans}/p/reverify`,method:'POST',body:'{}'},{path:`${base}/r/export`,method:'POST',body:'{}'},{path:`${base}/r`,body:'{}'},{path:`${base}/r/reverify`,method:'POST',body:'{"signature":"human"}'},...['limit=11','offset=129','limit=01','limit=1&limit=2','seed=x'].map(q=>({path:`${base}?${q}`}))])expect(schema.safeParse(p).success).toBe(false)})
})
