import {mkdtempSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {afterEach,it,expect,vi} from 'vitest'
import Database from '#repo/node_modules/better-sqlite3/lib/index.js'
import {SurveyQualityScoringWorkspaceService as Service} from '#repo/kun/src/engineering/survey-quality-scoring-workspace.ts'
import {fixture,model,custom,envelope} from './fixtures'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
import {readQualityScoring,exportQualityScoring,listQualityScorings,validateQualityScoringInput} from '#repo/src/renderer/src/agent/survey-quality-scoring-client.ts'
const request=vi.mocked(rendererRuntimeClient.runtimeRequest);afterEach(()=>{vi.unstubAllGlobals();request.mockReset()})
const sha=(x:any)=>createHash('sha256').update(x).digest('hex');function canonical(x:any):string{if(Array.isArray(x))return`[${x.map(canonical).join(',')}]`;if(x&&typeof x==='object')return`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}`;return JSON.stringify(x)}const digest=(x:any)=>sha(canonical(x));const response=(x:any)=>({ok:true,status:200,body:JSON.stringify(x)})
it.each(['full','pending','child-veto','multiple-sixty','partial','near60','sample128'])('real Runtime Unicode %s survives renderer without Buffer and retains trust boundaries',async name=>{const f=fixture(envelope(['partial','near60','sample128'].includes(name)?custom(name):model(name)));expect(f.record.requestJson).toBe(f.raw.toString());expect(f.record.declarationJson).toBe(f.q.declarationJson);expect(f.record.requestSha256).toBe(sha(f.raw));expect(f.record.declarationSha256).toBe(sha(f.q.declarationJson));expect(f.record).toMatchObject({engineeringDecision:'not-evaluated',evidenceAuthenticity:'not-verified',classificationAuthenticity:'not-verified',priorQualificationAuthenticity:'not-verified',formalResultsModified:false});if(name==='full')expect(f.record.result.result.score).toEqual({numerator:'9141',denominator:'100'});if(name==='partial')expect(f.record.scopeAssessment).toBe('partial-declared-product-profile');if(name==='pending'||name==='multiple-sixty')expect(f.summary.outcome).toBe('unavailable');if(name==='child-veto')expect(f.summary.outcome).toBe('nonconforming');if(name==='near60')expect(f.summary.outcome).toBe('calculated');if(name==='sample128')expect(f.record.result.result.grade).toBe('good');request.mockResolvedValue(response(f.record));vi.stubGlobal('Buffer',undefined);expect(await readQualityScoring(f.binding,f.summary)).toEqual(f.record);expect(await exportQualityScoring(f.binding,f.summary)).toEqual(f.record)})
it('rejects byte/parser ambiguity and lossy numeric precision without requesting',()=>{const f=fixture();for(const raw of [f.q.declarationJson.replace('"schemaVersion": 1','"schemaVersion":1,"\\u0073chemaVersion":1'),f.q.declarationJson.replace('"13/20"','0.65'),f.q.declarationJson.replace('"13/20"','"6.5e-1"'),f.q.declarationJson.replace('synthetic-point','\\ud800')])expect(validateQualityScoringInput(f.binding,{kind:'unit',declarationJson:raw,modelBasisStatement:'Independent evidence'})).toBe(false);expect(request).not.toHaveBeenCalled()})
it('rejects project contamination and pagination skipping or duplicates',async()=>{const f=fixture();for(const data of [{records:[f.summary],unavailable:[],nextOffset:10},{records:[f.summary],unavailable:[{id:f.summary.id,reason:'integrity'}],nextOffset:null},{records:[{...f.summary,projectRevision:2}],unavailable:[],nextOffset:null}]){request.mockResolvedValue(response(data));await expect(listQualityScorings(f.binding)).rejects.toMatchObject({reason:'invalid-response'})}})
it('max sample ten-record page replays at 191 units and remains browsable',()=>{const dir=mkdtempSync(join(tmpdir(),'quality-max-'));const p={id:'max-project',revision:1,workspace:dir};let ms=Date.parse('2026-09-20T00:00:00Z');const options={rootDir:dir,getProject:()=>p,nowIso:()=>new Date(ms).toISOString(),clockMs:()=>ms};let s=new Service(options);try{const ids=[];for(let i=0;i<10;i++){ms+=60001;ids.push(s.createRecord(p.id,Buffer.from(JSON.stringify(envelope(custom('sample128'),'maximum-sample-'+i)))).id)}s.close();s=new Service(options);const page=s.listRecords(p.id);expect(page.records).toHaveLength(10);expect(page.unavailable).toEqual([]);expect(page.nextOffset).toBeNull();expect(page.records.every(x=>x.scopeAssessment==='declared-sample-only')).toBe(true);const r=s.getRecord(p.id,ids[0]);expect(r.declaration.units).toHaveLength(128);s.getRecord(p.id,ids[1]);expect(()=>s.getRecord(p.id,ids[2])).toThrow('rate-limit')}finally{s.close();rmSync(dir,{recursive:true,force:true})}})
it('actual Runtime recomputation rejects altered exact score even after every unkeyed hash is restamped',()=>{const dir=mkdtempSync(join(tmpdir(),'quality-forge-'));const p={id:'forge-project',revision:1,workspace:dir};const s=new Service({rootDir:dir,getProject:()=>p});let db:any;try{const summary=s.createRecord(p.id,Buffer.from(JSON.stringify(envelope())));db=new Database(join(dir,'survey-quality-scoring.sqlite3'));const row=db.prepare('SELECT * FROM quality_scoring_records WHERE id=?').get(summary.id);const record=JSON.parse(row.data_json);record.result.result.score={numerator:'999999999999999999999999',denominator:'10000000000000000000000'};record.resultHash=digest(record.result);delete record.recordHash;record.recordHash=digest(record);row.record_hash=record.recordHash;row.data_json=JSON.stringify(record);const{storage_hash,request_bytes,declaration_bytes,...meta}=row;row.storage_hash=digest({...meta,request_bytes_sha256:sha(request_bytes),declaration_bytes_sha256:sha(declaration_bytes)});db.exec('DROP TRIGGER quality_scoring_records_no_update');const keys=Object.keys(row);db.prepare(`UPDATE quality_scoring_records SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).run(...keys.map(k=>row[k]),summary.id);expect(()=>s.getRecord(p.id,summary.id)).toThrow('integrity');expect(s.listRecords(p.id).unavailable).toEqual([{id:summary.id,reason:'integrity'}])}finally{db?.close();s.close();rmSync(dir,{recursive:true,force:true})}})
it('Runtime rejects invalid UTF-8 and preserves raw exact-byte idempotency',()=>{const dir=mkdtempSync(join(tmpdir(),'quality-bytes-'));const p={id:'bytes-project',revision:1,workspace:dir};const s=new Service({rootDir:dir,getProject:()=>p});try{expect(()=>s.createRecord(p.id,new Uint8Array([0xc0,0xaf]))).toThrow('validation');const raw=Buffer.from(JSON.stringify(envelope()));const first=s.createRecord(p.id,raw);expect(s.createRecord(p.id,raw)).toEqual(first);expect(()=>s.createRecord(p.id,Buffer.concat([raw,Buffer.from('\n')]))).toThrow('conflict');expect(s.getRecord(p.id,first.id).declarationJson).toContain('13/20')}finally{s.close();rmSync(dir,{recursive:true,force:true})}})
