import {mkdtempSync,rmSync,readFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Buffer as NodeBuffer} from 'node:buffer'
import {SurveyQualityScoringWorkspaceService as Service} from '#repo/kun/src/engineering/survey-quality-scoring-workspace.ts'
export const model=(name='full')=>JSON.parse(readFileSync(join(process.env.REVIEW_EVIDENCE!,`inputs/quality-${name}.json`),'utf8'))
export function custom(name:string){const q=model();if(name==='partial')q.leaves=q.leaves.map((l:any,i:number)=>i===0?l:{elementId:l.elementId,subelementId:l.subelementId,state:'excluded',reason:'Declared subset, independent synthetic fixture',evidenceRefs:['subset']});if(name==='near60'){q.leaves[0].record.model.items[0].m='0.999999999999999999999999';q.leaves[0].record.model.items.push({...q.leaves[0].record.model.items[0],id:'second-exact'})}if(name==='sample128'){const {unitId,unitType,leaves,inspectionStage,operation,declaredScope,...common}=q;return {...common,operation:'sample',inspectionStage:'detailed-sample',declaredScope:'explicit-sample-members',sampleId:'independent-sample',declaredUnitIds:Array.from({length:128},(_,i)=>'unit-'+i),units:Array.from({length:128},(_,i)=>({unitId:'unit-'+i,state:'qualified',declaredUnitCoverage:'full-product-profile',score:'89.999999999999999999999999',evidenceRefs:['independent-declared-full-unit']}))}}return q}
export function envelope(declaration=model(),key='independent-quality-integration'){return {kind:declaration.operation,acknowledged:true,expectedProjectRevision:1,idempotencyKey:key,declarationJson:' \n'+JSON.stringify(declaration,null,2)+'\t',modelBasisStatement:'独立合成检查😀\n并非工程批准。  '}}
export function fixture(q=envelope()){const dir=mkdtempSync(join(tmpdir(),'quality-independent-'));const project={id:'independent-quality-project',revision:1,workspace:dir+'/workspace'};const service=new Service({rootDir:dir,getProject:(id:string)=>id===project.id?project:null});try{const raw=NodeBuffer.from('\t'+JSON.stringify(q,null,2)+'\r\n');const summary=service.createRecord(project.id,raw),record=service.getRecord(project.id,summary.id);return{q,raw,summary,record,binding:{projectId:project.id,projectRevision:1,workspaceRoot:project.workspace}}}finally{service.close();rmSync(dir,{recursive:true,force:true})}}
