// @vitest-environment happy-dom
import {act,createElement} from '#repo/node_modules/react/index.js'
import {createRoot} from '#repo/node_modules/react-dom/client.js'
import {Buffer as NodeBuffer} from 'node:buffer'
import {webcrypto} from 'node:crypto'
import {afterEach,beforeEach,it,expect,vi} from 'vitest'
import {SurveyQualityScoringWorkspace} from '#repo/src/renderer/src/components/engineering/SurveyQualityScoringWorkspace.tsx'
import {fixture,model,custom,envelope} from './fixtures'
import i18n from '#repo/src/renderer/src/i18n.ts'
vi.mock('#repo/src/renderer/src/agent/runtime-client.ts',()=>({rendererRuntimeClient:{runtimeRequest:vi.fn()}}))
import {rendererRuntimeClient} from '#repo/src/renderer/src/agent/runtime-client.ts'
const request=vi.mocked(rendererRuntimeClient.runtimeRequest)
let root:any,host:HTMLDivElement
const t=(key:string)=>i18n.t(key,{ns:'qualityScoring'})
beforeEach(async()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});Object.defineProperty(crypto,'subtle',{configurable:true,value:webcrypto.subtle});await i18n.changeLanguage('en');host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{vi.unstubAllGlobals();await act(async()=>root.unmount());host.remove();request.mockReset()})
const button=(key:string)=>[...host.querySelectorAll('button')].find(n=>n.textContent===t(key))!
async function click(n:HTMLElement){await act(async()=>n.click())}
async function settle(fn:()=>void){let e;for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,5))});try{fn();return}catch(x){e=x}}throw e}
async function restore(f:any){request.mockImplementation(async path=>({ok:true,status:200,body:path.includes('?')?JSON.stringify({records:[f.summary],unavailable:[],nextOffset:null}):JSON.stringify(f.record)}));await act(async()=>root.render(createElement(SurveyQualityScoringWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('scoringHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(t('scoringRestore')))!);await settle(()=>expect(host.textContent).toContain(t('scoringSavedRecord')))}
it.each(['en','zh'])('renders partial exact score/grade as partial and unverified in %s without Buffer',async language=>{await i18n.changeLanguage(language);const f=fixture(envelope(custom('partial')));vi.stubGlobal('Buffer',undefined);await restore(f);const result=host.querySelector(`[aria-label="${t('scoringResult')}"]`)!;expect(result.textContent).toContain('80/1');expect(result.textContent).toContain(t('scopes.partial-declared-product-profile'));expect(result.textContent).toContain(t('scoringPartialGrade'));expect(result.textContent).toContain(t('scoringResultBoundary'));expect(result.textContent).toContain(t('scoringDeclaredYes'));expect(host.textContent).toContain(t('scoringBoundary'));expect(result.textContent).not.toMatch(/\bNaN\b|\bInfinity\b|\bundefined\b/);expect(result.textContent).not.toMatch(/scoring[A-Z]/);if(language==='en')expect(result.textContent).not.toMatch(/[㐀-鿿]/)})
it.each(['full','pending','child-veto','multiple-sixty'])('shows actual acceptance fixture %s with exact result and honest scope',async name=>{const f=fixture(envelope(model(name)));vi.stubGlobal('Buffer',undefined);await restore(f);const result=host.querySelector(`[aria-label="${t('scoringResult')}"]`)!;expect(result.textContent).toContain(t('states.'+f.summary.outcome));expect(result.textContent).toContain(t('scopes.'+f.summary.scopeAssessment));expect(result.textContent).toContain(t('reasons.'+f.record.result.result.reason));expect(result.querySelectorAll('tbody tr').length).toBe(f.record.result.trace.length);if(name==='full')expect(result.textContent).toContain('9141/100');else expect(result.textContent).not.toContain(t('scoringDeclaredYes'))})
it('keeps 24-decimal near-threshold fraction visible without rounding to 60',async()=>{const f=fixture(envelope(custom('near60')));await restore(f);const result=host.querySelector(`[aria-label="${t('scoringResult')}"]`)!;const exact=f.record.result.trace.find((x:any)=>x.nodeId==='mathematical-accuracy')!.result.score;expect(exact).not.toEqual({numerator:'60',denominator:'1'});expect(result.textContent).toContain(exact.numerator+'/'+exact.denominator);expect(result.textContent).toContain(t('scoringExactHint'))})
it('exports exact Unicode record without Buffer and suppresses delayed export after project switch',async()=>{const f=fixture(),save=vi.fn().mockResolvedValue({ok:true,path:'/review/质量.json'});Object.assign(window,{workwise:{saveWorkspaceFileAs:save}});vi.stubGlobal('Buffer',undefined);await restore(f);await click(button('scoringExport'));await settle(()=>expect(save).toHaveBeenCalledOnce());const payload=save.mock.calls[0][0];expect(NodeBuffer.from(payload.dataBase64,'base64').toString('utf8')).toBe(JSON.stringify(f.record)+'\n');expect(payload.workspaceRoot).toBe(f.binding.workspaceRoot);expect(request.mock.calls.at(-1)[0]).toMatch(/\/export$/);await settle(()=>expect(host.textContent).toContain('/review/质量.json'));let release:any;request.mockImplementationOnce(()=>new Promise(r=>release=r));await click(button('scoringExport'));await act(async()=>root.render(createElement(SurveyQualityScoringWorkspace,{binding:{...f.binding,projectId:'changed'},runtimeReady:true})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(save).toHaveBeenCalledOnce();expect(host.textContent).not.toContain(f.summary.id)})
it.each(['workspace','revision','runtime'])('drops late quality detail after %s change',async key=>{const f=fixture();let release:any;request.mockImplementation(async path=>path.includes('?')?{ok:true,status:200,body:JSON.stringify({records:[f.summary],unavailable:[],nextOffset:null})}:new Promise(r=>release=r));await act(async()=>root.render(createElement(SurveyQualityScoringWorkspace,{binding:f.binding,runtimeReady:true})));await click(button('scoringHistory'));await settle(()=>expect(host.textContent).toContain(f.summary.id));await click([...host.querySelectorAll('button')].find(n=>n.textContent?.startsWith(t('scoringRestore')))!);await act(async()=>root.render(createElement(SurveyQualityScoringWorkspace,{binding:{...f.binding,...(key==='workspace'?{workspaceRoot:'/changed'}:key==='revision'?{projectRevision:2}:{})},runtimeReady:key!=='runtime'})));await act(async()=>{release({ok:true,status:200,body:JSON.stringify(f.record)});await new Promise(r=>setTimeout(r,30))});expect(host.textContent).not.toContain(f.summary.id);expect(host.textContent).not.toContain(t('scoringSavedRecord'))})
it('restored height record labels its actual profile and stage independently of draft defaults',async()=>{const q=model();q.productProfileId='height-control-section';q.profileWeightTable=45;q.profileClassificationTable=46;q.unitType='section';const f=fixture(envelope(q));await restore(f);const heading=[...host.querySelectorAll('h4')].find(x=>x.textContent===t('scoringSavedRecord'))!;expect(heading.parentElement?.querySelector('p.font-medium')?.textContent).toBe(t('scoringHeight')+' · '+t('operations.unit')+' · GB/T 24356-2023')})
